//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Множество внешних запросов различного типа
 * <p>
 * <p>Java class for msg_TIncomingMessages complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="msg_TIncomingMessages">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;choice>
 *           &lt;element name="ids-message" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TIdentNotificationMessage"/>
 *           &lt;element name="state-request" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TStateRequestMessage"/>
 *           &lt;element name="type-request" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TTypeRequestMessage"/>
 *           &lt;element name="status-message" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TStatusMessage"/>
 *         &lt;/choice>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "msg_TIncomingMessages", propOrder = {
	"statusMessage",
	"typeRequest",
	"stateRequest",
	"idsMessage"
})
@XmlRootElement(name = "messages")
public class Messages {

   @XmlElement(name = "status-message")
   protected StatusMessage statusMessage;
   @XmlElement(name = "type-request")
   protected TypeRequest typeRequest;
   @XmlElement(name = "state-request")
   protected StateRequest stateRequest;
   @XmlElement(name = "ids-message")
   protected IdsMessage idsMessage;

   /**
	* Gets the value of the statusMessage property.
	*
	* @return possible object is
	* {@link StatusMessage }
	*/
   public StatusMessage getStatusMessage() {
	  return statusMessage;
   }

   /**
	* Sets the value of the statusMessage property.
	*
	* @param value allowed object is
	*              {@link StatusMessage }
	*/
   public void setStatusMessage(StatusMessage value) {
	  this.statusMessage = value;
   }

   /**
	* Gets the value of the typeRequest property.
	*
	* @return possible object is
	* {@link TypeRequest }
	*/
   public TypeRequest getTypeRequest() {
	  return typeRequest;
   }

   /**
	* Sets the value of the typeRequest property.
	*
	* @param value allowed object is
	*              {@link TypeRequest }
	*/
   public void setTypeRequest(TypeRequest value) {
	  this.typeRequest = value;
   }

   /**
	* Gets the value of the stateRequest property.
	*
	* @return possible object is
	* {@link StateRequest }
	*/
   public StateRequest getStateRequest() {
	  return stateRequest;
   }

   /**
	* Sets the value of the stateRequest property.
	*
	* @param value allowed object is
	*              {@link StateRequest }
	*/
   public void setStateRequest(StateRequest value) {
	  this.stateRequest = value;
   }

   /**
	* Gets the value of the idsMessage property.
	*
	* @return possible object is
	* {@link IdsMessage }
	*/
   public IdsMessage getIdsMessage() {
	  return idsMessage;
   }

   /**
	* Sets the value of the idsMessage property.
	*
	* @param value allowed object is
	*              {@link IdsMessage }
	*/
   public void setIdsMessage(IdsMessage value) {
	  this.idsMessage = value;
   }

}
