//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Уведомление об установке иденнтификатора объекта в одной из подсистем
 * <p>
 * <p>Java class for msg_TIdentSetNotification complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="msg_TIdentSetNotification">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="objectType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TObjectType"/>
 *         &lt;element name="identSet" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComponentIds"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "msg_TIdentSetNotification", propOrder = {
	"objectType",
	"identSet"
})
public class MsgTIdentSetNotification {

   @XmlElement(required = true)
   protected TObjectType objectType;
   @XmlElement(required = true)
   protected TComponentIds identSet;

   /**
	* Gets the value of the objectType property.
	*
	* @return possible object is
	* {@link TObjectType }
	*/
   public TObjectType getObjectType() {
	  return objectType;
   }

   /**
	* Sets the value of the objectType property.
	*
	* @param value allowed object is
	*              {@link TObjectType }
	*/
   public void setObjectType(TObjectType value) {
	  this.objectType = value;
   }

   /**
	* Gets the value of the identSet property.
	*
	* @return possible object is
	* {@link TComponentIds }
	*/
   public TComponentIds getIdentSet() {
	  return identSet;
   }

   /**
	* Sets the value of the identSet property.
	*
	* @param value allowed object is
	*              {@link TComponentIds }
	*/
   public void setIdentSet(TComponentIds value) {
	  this.identSet = value;
   }

}
