//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for msg_TEventName.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="msg_TEventName">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="CREATE"/>
 *     &lt;enumeration value="UPDATE"/>
 *     &lt;enumeration value="DELETE"/>
 *     &lt;enumeration value="NOP"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "msg_TEventName")
@XmlEnum
public enum MsgTEventName {


   /**
	* создание информационного объекта
	*/
   CREATE,

   /**
	* обновление информационного объекта
	*/
   UPDATE,

   /**
	* удаление информационного объекта
	*/
   DELETE,

   /**
	* объект не изменялся (специальный тип для связанных объектов)
	*/
   NOP;

   public String value() {
	  return name();
   }

   public static MsgTEventName fromValue(String v) {
	  return valueOf(v);
   }

}
