//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * объект сообщения, содержащий информацию об изменениях
 * <p>
 * <p>Java class for msg_TObjectMessageBody complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="msg_TObjectMessageBody">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice>
 *         &lt;element name="TAgencyOrganizationForm" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TAgencyOrganizationForm"/>
 *         &lt;element name="TRoadSurfaceType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRoadSurfaceType"/>
 *         &lt;element name="TMovementDirection" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TMovementDirection"/>
 *         &lt;element name="TCompensatoryPointType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TCompensatoryPointType"/>
 *         &lt;element name="TCompensatoryPoint" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TCompensatoryPoint"/>
 *         &lt;element name="TCompensatoryRoute" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TCompensatoryRoute"/>
 *         &lt;element name="TTransportStaticObjectType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TTransportStaticObjectType"/>
 *         &lt;element name="TTransportStaticObject" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TTransportStaticObject"/>
 *         &lt;element name="TTicketSalePoint" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TTicketSalePoint"/>
 *         &lt;element name="TVehicleType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TVehicleType"/>
 *         &lt;element name="TOrderKind" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TOrderKind"/>
 *         &lt;element name="TOrderType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TOrderType"/>
 *         &lt;element name="TRouteKind" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRouteKind"/>
 *         &lt;element name="TRouteState" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRouteState"/>
 *         &lt;element name="TRouteState2" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRouteState2"/>
 *         &lt;element name="TRouteTransportKind" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRouteTransportKind"/>
 *         &lt;element name="TRouteTransportationKind" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRouteTransportationKind"/>
 *         &lt;element name="TRouteTrajectoryType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRouteTrajectoryType"/>
 *         &lt;element name="TRouteVariantType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRouteVariantType"/>
 *         &lt;element name="TStopMode" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TStopMode"/>
 *         &lt;element name="TStopState" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TStopState"/>
 *         &lt;element name="TStopType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TStopType"/>
 *         &lt;element name="TTransportKind" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TTransportKind"/>
 *         &lt;element name="TRouteRoundType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRouteRoundType"/>
 *         &lt;element name="TRouteRound" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRouteRound"/>
 *         &lt;element name="TRouteNullRound" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRouteNullRound"/>
 *         &lt;element name="TRouteNullRoundType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRouteNullRoundType"/>
 *         &lt;element name="TBuilding" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TBuilding"/>
 *         &lt;element name="TStreet" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TStreet"/>
 *         &lt;element name="TDistrict" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TDistrict"/>
 *         &lt;element name="TRegion" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRegion"/>
 *         &lt;element name="TEGKODistrict" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TEGKODistrict"/>
 *         &lt;element name="TEGKORegion" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TEGKORegion"/>
 *         &lt;element name="TAgency" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TAgency"/>
 *         &lt;element name="TGraphNode" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TGraphNode"/>
 *         &lt;element name="TGraphSection" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TGraphSection"/>
 *         &lt;element name="TOrder" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TOrder"/>
 *         &lt;element name="TPark" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TPark"/>
 *         &lt;element name="TParkZone" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TParkZone"/>
 *         &lt;element name="TRouteTrajectory" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRouteTrajectory"/>
 *         &lt;element name="TRouteVariant" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRouteVariant"/>
 *         &lt;element name="TRoute" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRoute"/>
 *         &lt;element name="TStopPlace" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TStopPlace"/>
 *         &lt;element name="TStopZone" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TStopZone"/>
 *         &lt;element name="TStop" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TStop"/>
 *         &lt;element name="TTerminalStation" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TTerminalStation"/>
 *         &lt;element name="TTransportParking" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TTransportParking"/>
 *         &lt;element name="TTerminalPointZone" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TTerminalPointZone"/>
 *         &lt;element name="TRouteTrajectories2StopPlaces" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRouteTrajectories2StopPlaces"/>
 *         &lt;element name="TRouteTrajectories2GraphSections" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TRouteTrajectories2GraphSections"/>
 *         &lt;element name="TParks2Routes" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TParks2Routes"/>
 *         &lt;element name="TParks2VehicleTypes" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TParks2VehicleTypes"/>
 *         &lt;element name="TParks2Agencies" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TParks2Agencies"/>
 *         &lt;element name="TStopPavilion" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TStopPavilion"/>
 *         &lt;element name="TStopPavilionInstallation" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TStopPavilionInstallation"/>
 *         &lt;element name="TStopPavilionOrder" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TStopPavilionOrder"/>
 *         &lt;element name="TStopPavilionOrderType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TStopPavilionOrderType"/>
 *         &lt;element name="TStopPavilionType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TStopPavilionType"/>
 *         &lt;element name="TStopPavilionState" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TStopPavilionState"/>
 *         &lt;element name="TStopPavilionBalanceOrganization" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TStopPavilionBalanceOrganization"/>
 *         &lt;element name="TStopPavilionInstallOrganization" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TStopPavilionInstallOrganization"/>
 *         &lt;element name="TStopPavilionServiceOrganization" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TStopPavilionServiceOrganization"/>
 *       &lt;/choice>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "msg_TObjectMessageBody", propOrder = {
	"tStopPavilionServiceOrganization",
	"tStopPavilionInstallOrganization",
	"tStopPavilionBalanceOrganization",
	"tStopPavilionState",
	"tStopPavilionType",
	"tStopPavilionOrderType",
	"tStopPavilionOrder",
	"tStopPavilionInstallation",
	"tStopPavilion",
	"tParks2Agencies",
	"tParks2VehicleTypes",
	"tParks2Routes",
	"tRouteTrajectories2GraphSections",
	"tRouteTrajectories2StopPlaces",
	"tTerminalPointZone",
	"tTransportParking",
	"tTerminalStation",
	"tStop",
	"tStopZone",
	"tStopPlace",
	"tRoute",
	"tRouteVariant",
	"tRouteTrajectory",
	"tParkZone",
	"tPark",
	"tOrder",
	"tGraphSection",
	"tGraphNode",
	"tAgency",
	"tegkoRegion",
	"tegkoDistrict",
	"tRegion",
	"tDistrict",
	"tStreet",
	"tBuilding",
	"tRouteNullRoundType",
	"tRouteNullRound",
	"tRouteRound",
	"tRouteRoundType",
	"tTransportKind",
	"tStopType",
	"tStopState",
	"tStopMode",
	"tRouteVariantType",
	"tRouteTrajectoryType",
	"tRouteTransportationKind",
	"tRouteTransportKind",
	"tRouteState2",
	"tRouteState",
	"tRouteKind",
	"tOrderType",
	"tOrderKind",
	"tVehicleType",
	"tTicketSalePoint",
	"tTransportStaticObject",
	"tTransportStaticObjectType",
	"tCompensatoryRoute",
	"tCompensatoryPoint",
	"tCompensatoryPointType",
	"tMovementDirection",
	"tRoadSurfaceType",
	"tAgencyOrganizationForm"
})
public class MsgTObjectMessageBody {

   @XmlElement(name = "TStopPavilionServiceOrganization")
   protected TStopPavilionServiceOrganization tStopPavilionServiceOrganization;
   @XmlElement(name = "TStopPavilionInstallOrganization")
   protected TStopPavilionInstallOrganization tStopPavilionInstallOrganization;
   @XmlElement(name = "TStopPavilionBalanceOrganization")
   protected TStopPavilionBalanceOrganization tStopPavilionBalanceOrganization;
   @XmlElement(name = "TStopPavilionState")
   protected TStopPavilionState tStopPavilionState;
   @XmlElement(name = "TStopPavilionType")
   protected TStopPavilionType tStopPavilionType;
   @XmlElement(name = "TStopPavilionOrderType")
   protected TStopPavilionOrderType tStopPavilionOrderType;
   @XmlElement(name = "TStopPavilionOrder")
   protected TStopPavilionOrder tStopPavilionOrder;
   @XmlElement(name = "TStopPavilionInstallation")
   protected TStopPavilionInstallation tStopPavilionInstallation;
   @XmlElement(name = "TStopPavilion")
   protected TStopPavilion tStopPavilion;
   @XmlElement(name = "TParks2Agencies")
   protected TParks2Agencies tParks2Agencies;
   @XmlElement(name = "TParks2VehicleTypes")
   protected TParks2VehicleTypes tParks2VehicleTypes;
   @XmlElement(name = "TParks2Routes")
   protected TParks2Routes tParks2Routes;
   @XmlElement(name = "TRouteTrajectories2GraphSections")
   protected TRouteTrajectories2GraphSections tRouteTrajectories2GraphSections;
   @XmlElement(name = "TRouteTrajectories2StopPlaces")
   protected TRouteTrajectories2StopPlaces tRouteTrajectories2StopPlaces;
   @XmlElement(name = "TTerminalPointZone")
   protected TTerminalPointZone tTerminalPointZone;
   @XmlElement(name = "TTransportParking")
   protected TTransportParking tTransportParking;
   @XmlElement(name = "TTerminalStation")
   protected TTerminalStation tTerminalStation;
   @XmlElement(name = "TStop")
   protected TStop tStop;
   @XmlElement(name = "TStopZone")
   protected TStopZone tStopZone;
   @XmlElement(name = "TStopPlace")
   protected TStopPlace tStopPlace;
   @XmlElement(name = "TRoute")
   protected TRoute tRoute;
   @XmlElement(name = "TRouteVariant")
   protected TRouteVariant tRouteVariant;
   @XmlElement(name = "TRouteTrajectory")
   protected TRouteTrajectory tRouteTrajectory;
   @XmlElement(name = "TParkZone")
   protected TParkZone tParkZone;
   @XmlElement(name = "TPark")
   protected TPark tPark;
   @XmlElement(name = "TOrder")
   protected TOrder tOrder;
   @XmlElement(name = "TGraphSection")
   protected TGraphSection tGraphSection;
   @XmlElement(name = "TGraphNode")
   protected TGraphNode tGraphNode;
   @XmlElement(name = "TAgency")
   protected TAgency tAgency;
   @XmlElement(name = "TEGKORegion")
   protected TEGKORegion tegkoRegion;
   @XmlElement(name = "TEGKODistrict")
   protected TEGKODistrict tegkoDistrict;
   @XmlElement(name = "TRegion")
   protected TRegion tRegion;
   @XmlElement(name = "TDistrict")
   protected TDistrict tDistrict;
   @XmlElement(name = "TStreet")
   protected TStreet tStreet;
   @XmlElement(name = "TBuilding")
   protected TBuilding tBuilding;
   @XmlElement(name = "TRouteNullRoundType")
   protected TRouteNullRoundType tRouteNullRoundType;
   @XmlElement(name = "TRouteNullRound")
   protected TRouteNullRound tRouteNullRound;
   @XmlElement(name = "TRouteRound")
   protected TRouteRound tRouteRound;
   @XmlElement(name = "TRouteRoundType")
   protected TRouteRoundType tRouteRoundType;
   @XmlElement(name = "TTransportKind")
   protected TTransportKind tTransportKind;
   @XmlElement(name = "TStopType")
   protected TStopType tStopType;
   @XmlElement(name = "TStopState")
   protected TStopState tStopState;
   @XmlElement(name = "TStopMode")
   protected TStopMode tStopMode;
   @XmlElement(name = "TRouteVariantType")
   protected TRouteVariantType tRouteVariantType;
   @XmlElement(name = "TRouteTrajectoryType")
   protected TRouteTrajectoryType tRouteTrajectoryType;
   @XmlElement(name = "TRouteTransportationKind")
   protected TRouteTransportationKind tRouteTransportationKind;
   @XmlElement(name = "TRouteTransportKind")
   protected TRouteTransportKind tRouteTransportKind;
   @XmlElement(name = "TRouteState2")
   protected TRouteState2 tRouteState2;
   @XmlElement(name = "TRouteState")
   protected TRouteState tRouteState;
   @XmlElement(name = "TRouteKind")
   protected TRouteKind tRouteKind;
   @XmlElement(name = "TOrderType")
   protected TOrderType tOrderType;
   @XmlElement(name = "TOrderKind")
   protected TOrderKind tOrderKind;
   @XmlElement(name = "TVehicleType")
   protected TVehicleType tVehicleType;
   @XmlElement(name = "TTicketSalePoint")
   protected TTicketSalePoint tTicketSalePoint;
   @XmlElement(name = "TTransportStaticObject")
   protected TTransportStaticObject tTransportStaticObject;
   @XmlElement(name = "TTransportStaticObjectType")
   protected TTransportStaticObjectType tTransportStaticObjectType;
   @XmlElement(name = "TCompensatoryRoute")
   protected TCompensatoryRoute tCompensatoryRoute;
   @XmlElement(name = "TCompensatoryPoint")
   protected TCompensatoryPoint tCompensatoryPoint;
   @XmlElement(name = "TCompensatoryPointType")
   protected TCompensatoryPointType tCompensatoryPointType;
   @XmlElement(name = "TMovementDirection")
   protected TMovementDirection tMovementDirection;
   @XmlElement(name = "TRoadSurfaceType")
   protected TRoadSurfaceType tRoadSurfaceType;
   @XmlElement(name = "TAgencyOrganizationForm")
   protected TAgencyOrganizationForm tAgencyOrganizationForm;

   /**
	* Gets the value of the tStopPavilionServiceOrganization property.
	*
	* @return possible object is
	* {@link TStopPavilionServiceOrganization }
	*/
   public TStopPavilionServiceOrganization getTStopPavilionServiceOrganization() {
	  return tStopPavilionServiceOrganization;
   }

   /**
	* Sets the value of the tStopPavilionServiceOrganization property.
	*
	* @param value allowed object is
	*              {@link TStopPavilionServiceOrganization }
	*/
   public void setTStopPavilionServiceOrganization(TStopPavilionServiceOrganization value) {
	  this.tStopPavilionServiceOrganization = value;
   }

   /**
	* Gets the value of the tStopPavilionInstallOrganization property.
	*
	* @return possible object is
	* {@link TStopPavilionInstallOrganization }
	*/
   public TStopPavilionInstallOrganization getTStopPavilionInstallOrganization() {
	  return tStopPavilionInstallOrganization;
   }

   /**
	* Sets the value of the tStopPavilionInstallOrganization property.
	*
	* @param value allowed object is
	*              {@link TStopPavilionInstallOrganization }
	*/
   public void setTStopPavilionInstallOrganization(TStopPavilionInstallOrganization value) {
	  this.tStopPavilionInstallOrganization = value;
   }

   /**
	* Gets the value of the tStopPavilionBalanceOrganization property.
	*
	* @return possible object is
	* {@link TStopPavilionBalanceOrganization }
	*/
   public TStopPavilionBalanceOrganization getTStopPavilionBalanceOrganization() {
	  return tStopPavilionBalanceOrganization;
   }

   /**
	* Sets the value of the tStopPavilionBalanceOrganization property.
	*
	* @param value allowed object is
	*              {@link TStopPavilionBalanceOrganization }
	*/
   public void setTStopPavilionBalanceOrganization(TStopPavilionBalanceOrganization value) {
	  this.tStopPavilionBalanceOrganization = value;
   }

   /**
	* Gets the value of the tStopPavilionState property.
	*
	* @return possible object is
	* {@link TStopPavilionState }
	*/
   public TStopPavilionState getTStopPavilionState() {
	  return tStopPavilionState;
   }

   /**
	* Sets the value of the tStopPavilionState property.
	*
	* @param value allowed object is
	*              {@link TStopPavilionState }
	*/
   public void setTStopPavilionState(TStopPavilionState value) {
	  this.tStopPavilionState = value;
   }

   /**
	* Gets the value of the tStopPavilionType property.
	*
	* @return possible object is
	* {@link TStopPavilionType }
	*/
   public TStopPavilionType getTStopPavilionType() {
	  return tStopPavilionType;
   }

   /**
	* Sets the value of the tStopPavilionType property.
	*
	* @param value allowed object is
	*              {@link TStopPavilionType }
	*/
   public void setTStopPavilionType(TStopPavilionType value) {
	  this.tStopPavilionType = value;
   }

   /**
	* Gets the value of the tStopPavilionOrderType property.
	*
	* @return possible object is
	* {@link TStopPavilionOrderType }
	*/
   public TStopPavilionOrderType getTStopPavilionOrderType() {
	  return tStopPavilionOrderType;
   }

   /**
	* Sets the value of the tStopPavilionOrderType property.
	*
	* @param value allowed object is
	*              {@link TStopPavilionOrderType }
	*/
   public void setTStopPavilionOrderType(TStopPavilionOrderType value) {
	  this.tStopPavilionOrderType = value;
   }

   /**
	* Gets the value of the tStopPavilionOrder property.
	*
	* @return possible object is
	* {@link TStopPavilionOrder }
	*/
   public TStopPavilionOrder getTStopPavilionOrder() {
	  return tStopPavilionOrder;
   }

   /**
	* Sets the value of the tStopPavilionOrder property.
	*
	* @param value allowed object is
	*              {@link TStopPavilionOrder }
	*/
   public void setTStopPavilionOrder(TStopPavilionOrder value) {
	  this.tStopPavilionOrder = value;
   }

   /**
	* Gets the value of the tStopPavilionInstallation property.
	*
	* @return possible object is
	* {@link TStopPavilionInstallation }
	*/
   public TStopPavilionInstallation getTStopPavilionInstallation() {
	  return tStopPavilionInstallation;
   }

   /**
	* Sets the value of the tStopPavilionInstallation property.
	*
	* @param value allowed object is
	*              {@link TStopPavilionInstallation }
	*/
   public void setTStopPavilionInstallation(TStopPavilionInstallation value) {
	  this.tStopPavilionInstallation = value;
   }

   /**
	* Gets the value of the tStopPavilion property.
	*
	* @return possible object is
	* {@link TStopPavilion }
	*/
   public TStopPavilion getTStopPavilion() {
	  return tStopPavilion;
   }

   /**
	* Sets the value of the tStopPavilion property.
	*
	* @param value allowed object is
	*              {@link TStopPavilion }
	*/
   public void setTStopPavilion(TStopPavilion value) {
	  this.tStopPavilion = value;
   }

   /**
	* Gets the value of the tParks2Agencies property.
	*
	* @return possible object is
	* {@link TParks2Agencies }
	*/
   public TParks2Agencies getTParks2Agencies() {
	  return tParks2Agencies;
   }

   /**
	* Sets the value of the tParks2Agencies property.
	*
	* @param value allowed object is
	*              {@link TParks2Agencies }
	*/
   public void setTParks2Agencies(TParks2Agencies value) {
	  this.tParks2Agencies = value;
   }

   /**
	* Gets the value of the tParks2VehicleTypes property.
	*
	* @return possible object is
	* {@link TParks2VehicleTypes }
	*/
   public TParks2VehicleTypes getTParks2VehicleTypes() {
	  return tParks2VehicleTypes;
   }

   /**
	* Sets the value of the tParks2VehicleTypes property.
	*
	* @param value allowed object is
	*              {@link TParks2VehicleTypes }
	*/
   public void setTParks2VehicleTypes(TParks2VehicleTypes value) {
	  this.tParks2VehicleTypes = value;
   }

   /**
	* Gets the value of the tParks2Routes property.
	*
	* @return possible object is
	* {@link TParks2Routes }
	*/
   public TParks2Routes getTParks2Routes() {
	  return tParks2Routes;
   }

   /**
	* Sets the value of the tParks2Routes property.
	*
	* @param value allowed object is
	*              {@link TParks2Routes }
	*/
   public void setTParks2Routes(TParks2Routes value) {
	  this.tParks2Routes = value;
   }

   /**
	* Gets the value of the tRouteTrajectories2GraphSections property.
	*
	* @return possible object is
	* {@link TRouteTrajectories2GraphSections }
	*/
   public TRouteTrajectories2GraphSections getTRouteTrajectories2GraphSections() {
	  return tRouteTrajectories2GraphSections;
   }

   /**
	* Sets the value of the tRouteTrajectories2GraphSections property.
	*
	* @param value allowed object is
	*              {@link TRouteTrajectories2GraphSections }
	*/
   public void setTRouteTrajectories2GraphSections(TRouteTrajectories2GraphSections value) {
	  this.tRouteTrajectories2GraphSections = value;
   }

   /**
	* Gets the value of the tRouteTrajectories2StopPlaces property.
	*
	* @return possible object is
	* {@link TRouteTrajectories2StopPlaces }
	*/
   public TRouteTrajectories2StopPlaces getTRouteTrajectories2StopPlaces() {
	  return tRouteTrajectories2StopPlaces;
   }

   /**
	* Sets the value of the tRouteTrajectories2StopPlaces property.
	*
	* @param value allowed object is
	*              {@link TRouteTrajectories2StopPlaces }
	*/
   public void setTRouteTrajectories2StopPlaces(TRouteTrajectories2StopPlaces value) {
	  this.tRouteTrajectories2StopPlaces = value;
   }

   /**
	* Gets the value of the tTerminalPointZone property.
	*
	* @return possible object is
	* {@link TTerminalPointZone }
	*/
   public TTerminalPointZone getTTerminalPointZone() {
	  return tTerminalPointZone;
   }

   /**
	* Sets the value of the tTerminalPointZone property.
	*
	* @param value allowed object is
	*              {@link TTerminalPointZone }
	*/
   public void setTTerminalPointZone(TTerminalPointZone value) {
	  this.tTerminalPointZone = value;
   }

   /**
	* Gets the value of the tTransportParking property.
	*
	* @return possible object is
	* {@link TTransportParking }
	*/
   public TTransportParking getTTransportParking() {
	  return tTransportParking;
   }

   /**
	* Sets the value of the tTransportParking property.
	*
	* @param value allowed object is
	*              {@link TTransportParking }
	*/
   public void setTTransportParking(TTransportParking value) {
	  this.tTransportParking = value;
   }

   /**
	* Gets the value of the tTerminalStation property.
	*
	* @return possible object is
	* {@link TTerminalStation }
	*/
   public TTerminalStation getTTerminalStation() {
	  return tTerminalStation;
   }

   /**
	* Sets the value of the tTerminalStation property.
	*
	* @param value allowed object is
	*              {@link TTerminalStation }
	*/
   public void setTTerminalStation(TTerminalStation value) {
	  this.tTerminalStation = value;
   }

   /**
	* Gets the value of the tStop property.
	*
	* @return possible object is
	* {@link TStop }
	*/
   public TStop getTStop() {
	  return tStop;
   }

   /**
	* Sets the value of the tStop property.
	*
	* @param value allowed object is
	*              {@link TStop }
	*/
   public void setTStop(TStop value) {
	  this.tStop = value;
   }

   /**
	* Gets the value of the tStopZone property.
	*
	* @return possible object is
	* {@link TStopZone }
	*/
   public TStopZone getTStopZone() {
	  return tStopZone;
   }

   /**
	* Sets the value of the tStopZone property.
	*
	* @param value allowed object is
	*              {@link TStopZone }
	*/
   public void setTStopZone(TStopZone value) {
	  this.tStopZone = value;
   }

   /**
	* Gets the value of the tStopPlace property.
	*
	* @return possible object is
	* {@link TStopPlace }
	*/
   public TStopPlace getTStopPlace() {
	  return tStopPlace;
   }

   /**
	* Sets the value of the tStopPlace property.
	*
	* @param value allowed object is
	*              {@link TStopPlace }
	*/
   public void setTStopPlace(TStopPlace value) {
	  this.tStopPlace = value;
   }

   /**
	* Gets the value of the tRoute property.
	*
	* @return possible object is
	* {@link TRoute }
	*/
   public TRoute getTRoute() {
	  return tRoute;
   }

   /**
	* Sets the value of the tRoute property.
	*
	* @param value allowed object is
	*              {@link TRoute }
	*/
   public void setTRoute(TRoute value) {
	  this.tRoute = value;
   }

   /**
	* Gets the value of the tRouteVariant property.
	*
	* @return possible object is
	* {@link TRouteVariant }
	*/
   public TRouteVariant getTRouteVariant() {
	  return tRouteVariant;
   }

   /**
	* Sets the value of the tRouteVariant property.
	*
	* @param value allowed object is
	*              {@link TRouteVariant }
	*/
   public void setTRouteVariant(TRouteVariant value) {
	  this.tRouteVariant = value;
   }

   /**
	* Gets the value of the tRouteTrajectory property.
	*
	* @return possible object is
	* {@link TRouteTrajectory }
	*/
   public TRouteTrajectory getTRouteTrajectory() {
	  return tRouteTrajectory;
   }

   /**
	* Sets the value of the tRouteTrajectory property.
	*
	* @param value allowed object is
	*              {@link TRouteTrajectory }
	*/
   public void setTRouteTrajectory(TRouteTrajectory value) {
	  this.tRouteTrajectory = value;
   }

   /**
	* Gets the value of the tParkZone property.
	*
	* @return possible object is
	* {@link TParkZone }
	*/
   public TParkZone getTParkZone() {
	  return tParkZone;
   }

   /**
	* Sets the value of the tParkZone property.
	*
	* @param value allowed object is
	*              {@link TParkZone }
	*/
   public void setTParkZone(TParkZone value) {
	  this.tParkZone = value;
   }

   /**
	* Gets the value of the tPark property.
	*
	* @return possible object is
	* {@link TPark }
	*/
   public TPark getTPark() {
	  return tPark;
   }

   /**
	* Sets the value of the tPark property.
	*
	* @param value allowed object is
	*              {@link TPark }
	*/
   public void setTPark(TPark value) {
	  this.tPark = value;
   }

   /**
	* Gets the value of the tOrder property.
	*
	* @return possible object is
	* {@link TOrder }
	*/
   public TOrder getTOrder() {
	  return tOrder;
   }

   /**
	* Sets the value of the tOrder property.
	*
	* @param value allowed object is
	*              {@link TOrder }
	*/
   public void setTOrder(TOrder value) {
	  this.tOrder = value;
   }

   /**
	* Gets the value of the tGraphSection property.
	*
	* @return possible object is
	* {@link TGraphSection }
	*/
   public TGraphSection getTGraphSection() {
	  return tGraphSection;
   }

   /**
	* Sets the value of the tGraphSection property.
	*
	* @param value allowed object is
	*              {@link TGraphSection }
	*/
   public void setTGraphSection(TGraphSection value) {
	  this.tGraphSection = value;
   }

   /**
	* Gets the value of the tGraphNode property.
	*
	* @return possible object is
	* {@link TGraphNode }
	*/
   public TGraphNode getTGraphNode() {
	  return tGraphNode;
   }

   /**
	* Sets the value of the tGraphNode property.
	*
	* @param value allowed object is
	*              {@link TGraphNode }
	*/
   public void setTGraphNode(TGraphNode value) {
	  this.tGraphNode = value;
   }

   /**
	* Gets the value of the tAgency property.
	*
	* @return possible object is
	* {@link TAgency }
	*/
   public TAgency getTAgency() {
	  return tAgency;
   }

   /**
	* Sets the value of the tAgency property.
	*
	* @param value allowed object is
	*              {@link TAgency }
	*/
   public void setTAgency(TAgency value) {
	  this.tAgency = value;
   }

   /**
	* Gets the value of the tegkoRegion property.
	*
	* @return possible object is
	* {@link TEGKORegion }
	*/
   public TEGKORegion getTEGKORegion() {
	  return tegkoRegion;
   }

   /**
	* Sets the value of the tegkoRegion property.
	*
	* @param value allowed object is
	*              {@link TEGKORegion }
	*/
   public void setTEGKORegion(TEGKORegion value) {
	  this.tegkoRegion = value;
   }

   /**
	* Gets the value of the tegkoDistrict property.
	*
	* @return possible object is
	* {@link TEGKODistrict }
	*/
   public TEGKODistrict getTEGKODistrict() {
	  return tegkoDistrict;
   }

   /**
	* Sets the value of the tegkoDistrict property.
	*
	* @param value allowed object is
	*              {@link TEGKODistrict }
	*/
   public void setTEGKODistrict(TEGKODistrict value) {
	  this.tegkoDistrict = value;
   }

   /**
	* Gets the value of the tRegion property.
	*
	* @return possible object is
	* {@link TRegion }
	*/
   public TRegion getTRegion() {
	  return tRegion;
   }

   /**
	* Sets the value of the tRegion property.
	*
	* @param value allowed object is
	*              {@link TRegion }
	*/
   public void setTRegion(TRegion value) {
	  this.tRegion = value;
   }

   /**
	* Gets the value of the tDistrict property.
	*
	* @return possible object is
	* {@link TDistrict }
	*/
   public TDistrict getTDistrict() {
	  return tDistrict;
   }

   /**
	* Sets the value of the tDistrict property.
	*
	* @param value allowed object is
	*              {@link TDistrict }
	*/
   public void setTDistrict(TDistrict value) {
	  this.tDistrict = value;
   }

   /**
	* Gets the value of the tStreet property.
	*
	* @return possible object is
	* {@link TStreet }
	*/
   public TStreet getTStreet() {
	  return tStreet;
   }

   /**
	* Sets the value of the tStreet property.
	*
	* @param value allowed object is
	*              {@link TStreet }
	*/
   public void setTStreet(TStreet value) {
	  this.tStreet = value;
   }

   /**
	* Gets the value of the tBuilding property.
	*
	* @return possible object is
	* {@link TBuilding }
	*/
   public TBuilding getTBuilding() {
	  return tBuilding;
   }

   /**
	* Sets the value of the tBuilding property.
	*
	* @param value allowed object is
	*              {@link TBuilding }
	*/
   public void setTBuilding(TBuilding value) {
	  this.tBuilding = value;
   }

   /**
	* Gets the value of the tRouteNullRoundType property.
	*
	* @return possible object is
	* {@link TRouteNullRoundType }
	*/
   public TRouteNullRoundType getTRouteNullRoundType() {
	  return tRouteNullRoundType;
   }

   /**
	* Sets the value of the tRouteNullRoundType property.
	*
	* @param value allowed object is
	*              {@link TRouteNullRoundType }
	*/
   public void setTRouteNullRoundType(TRouteNullRoundType value) {
	  this.tRouteNullRoundType = value;
   }

   /**
	* Gets the value of the tRouteNullRound property.
	*
	* @return possible object is
	* {@link TRouteNullRound }
	*/
   public TRouteNullRound getTRouteNullRound() {
	  return tRouteNullRound;
   }

   /**
	* Sets the value of the tRouteNullRound property.
	*
	* @param value allowed object is
	*              {@link TRouteNullRound }
	*/
   public void setTRouteNullRound(TRouteNullRound value) {
	  this.tRouteNullRound = value;
   }

   /**
	* Gets the value of the tRouteRound property.
	*
	* @return possible object is
	* {@link TRouteRound }
	*/
   public TRouteRound getTRouteRound() {
	  return tRouteRound;
   }

   /**
	* Sets the value of the tRouteRound property.
	*
	* @param value allowed object is
	*              {@link TRouteRound }
	*/
   public void setTRouteRound(TRouteRound value) {
	  this.tRouteRound = value;
   }

   /**
	* Gets the value of the tRouteRoundType property.
	*
	* @return possible object is
	* {@link TRouteRoundType }
	*/
   public TRouteRoundType getTRouteRoundType() {
	  return tRouteRoundType;
   }

   /**
	* Sets the value of the tRouteRoundType property.
	*
	* @param value allowed object is
	*              {@link TRouteRoundType }
	*/
   public void setTRouteRoundType(TRouteRoundType value) {
	  this.tRouteRoundType = value;
   }

   /**
	* Gets the value of the tTransportKind property.
	*
	* @return possible object is
	* {@link TTransportKind }
	*/
   public TTransportKind getTTransportKind() {
	  return tTransportKind;
   }

   /**
	* Sets the value of the tTransportKind property.
	*
	* @param value allowed object is
	*              {@link TTransportKind }
	*/
   public void setTTransportKind(TTransportKind value) {
	  this.tTransportKind = value;
   }

   /**
	* Gets the value of the tStopType property.
	*
	* @return possible object is
	* {@link TStopType }
	*/
   public TStopType getTStopType() {
	  return tStopType;
   }

   /**
	* Sets the value of the tStopType property.
	*
	* @param value allowed object is
	*              {@link TStopType }
	*/
   public void setTStopType(TStopType value) {
	  this.tStopType = value;
   }

   /**
	* Gets the value of the tStopState property.
	*
	* @return possible object is
	* {@link TStopState }
	*/
   public TStopState getTStopState() {
	  return tStopState;
   }

   /**
	* Sets the value of the tStopState property.
	*
	* @param value allowed object is
	*              {@link TStopState }
	*/
   public void setTStopState(TStopState value) {
	  this.tStopState = value;
   }

   /**
	* Gets the value of the tStopMode property.
	*
	* @return possible object is
	* {@link TStopMode }
	*/
   public TStopMode getTStopMode() {
	  return tStopMode;
   }

   /**
	* Sets the value of the tStopMode property.
	*
	* @param value allowed object is
	*              {@link TStopMode }
	*/
   public void setTStopMode(TStopMode value) {
	  this.tStopMode = value;
   }

   /**
	* Gets the value of the tRouteVariantType property.
	*
	* @return possible object is
	* {@link TRouteVariantType }
	*/
   public TRouteVariantType getTRouteVariantType() {
	  return tRouteVariantType;
   }

   /**
	* Sets the value of the tRouteVariantType property.
	*
	* @param value allowed object is
	*              {@link TRouteVariantType }
	*/
   public void setTRouteVariantType(TRouteVariantType value) {
	  this.tRouteVariantType = value;
   }

   /**
	* Gets the value of the tRouteTrajectoryType property.
	*
	* @return possible object is
	* {@link TRouteTrajectoryType }
	*/
   public TRouteTrajectoryType getTRouteTrajectoryType() {
	  return tRouteTrajectoryType;
   }

   /**
	* Sets the value of the tRouteTrajectoryType property.
	*
	* @param value allowed object is
	*              {@link TRouteTrajectoryType }
	*/
   public void setTRouteTrajectoryType(TRouteTrajectoryType value) {
	  this.tRouteTrajectoryType = value;
   }

   /**
	* Gets the value of the tRouteTransportationKind property.
	*
	* @return possible object is
	* {@link TRouteTransportationKind }
	*/
   public TRouteTransportationKind getTRouteTransportationKind() {
	  return tRouteTransportationKind;
   }

   /**
	* Sets the value of the tRouteTransportationKind property.
	*
	* @param value allowed object is
	*              {@link TRouteTransportationKind }
	*/
   public void setTRouteTransportationKind(TRouteTransportationKind value) {
	  this.tRouteTransportationKind = value;
   }

   /**
	* Gets the value of the tRouteTransportKind property.
	*
	* @return possible object is
	* {@link TRouteTransportKind }
	*/
   public TRouteTransportKind getTRouteTransportKind() {
	  return tRouteTransportKind;
   }

   /**
	* Sets the value of the tRouteTransportKind property.
	*
	* @param value allowed object is
	*              {@link TRouteTransportKind }
	*/
   public void setTRouteTransportKind(TRouteTransportKind value) {
	  this.tRouteTransportKind = value;
   }

   /**
	* Gets the value of the tRouteState2 property.
	*
	* @return possible object is
	* {@link TRouteState2 }
	*/
   public TRouteState2 getTRouteState2() {
	  return tRouteState2;
   }

   /**
	* Sets the value of the tRouteState2 property.
	*
	* @param value allowed object is
	*              {@link TRouteState2 }
	*/
   public void setTRouteState2(TRouteState2 value) {
	  this.tRouteState2 = value;
   }

   /**
	* Gets the value of the tRouteState property.
	*
	* @return possible object is
	* {@link TRouteState }
	*/
   public TRouteState getTRouteState() {
	  return tRouteState;
   }

   /**
	* Sets the value of the tRouteState property.
	*
	* @param value allowed object is
	*              {@link TRouteState }
	*/
   public void setTRouteState(TRouteState value) {
	  this.tRouteState = value;
   }

   /**
	* Gets the value of the tRouteKind property.
	*
	* @return possible object is
	* {@link TRouteKind }
	*/
   public TRouteKind getTRouteKind() {
	  return tRouteKind;
   }

   /**
	* Sets the value of the tRouteKind property.
	*
	* @param value allowed object is
	*              {@link TRouteKind }
	*/
   public void setTRouteKind(TRouteKind value) {
	  this.tRouteKind = value;
   }

   /**
	* Gets the value of the tOrderType property.
	*
	* @return possible object is
	* {@link TOrderType }
	*/
   public TOrderType getTOrderType() {
	  return tOrderType;
   }

   /**
	* Sets the value of the tOrderType property.
	*
	* @param value allowed object is
	*              {@link TOrderType }
	*/
   public void setTOrderType(TOrderType value) {
	  this.tOrderType = value;
   }

   /**
	* Gets the value of the tOrderKind property.
	*
	* @return possible object is
	* {@link TOrderKind }
	*/
   public TOrderKind getTOrderKind() {
	  return tOrderKind;
   }

   /**
	* Sets the value of the tOrderKind property.
	*
	* @param value allowed object is
	*              {@link TOrderKind }
	*/
   public void setTOrderKind(TOrderKind value) {
	  this.tOrderKind = value;
   }

   /**
	* Gets the value of the tVehicleType property.
	*
	* @return possible object is
	* {@link TVehicleType }
	*/
   public TVehicleType getTVehicleType() {
	  return tVehicleType;
   }

   /**
	* Sets the value of the tVehicleType property.
	*
	* @param value allowed object is
	*              {@link TVehicleType }
	*/
   public void setTVehicleType(TVehicleType value) {
	  this.tVehicleType = value;
   }

   /**
	* Gets the value of the tTicketSalePoint property.
	*
	* @return possible object is
	* {@link TTicketSalePoint }
	*/
   public TTicketSalePoint getTTicketSalePoint() {
	  return tTicketSalePoint;
   }

   /**
	* Sets the value of the tTicketSalePoint property.
	*
	* @param value allowed object is
	*              {@link TTicketSalePoint }
	*/
   public void setTTicketSalePoint(TTicketSalePoint value) {
	  this.tTicketSalePoint = value;
   }

   /**
	* Gets the value of the tTransportStaticObject property.
	*
	* @return possible object is
	* {@link TTransportStaticObject }
	*/
   public TTransportStaticObject getTTransportStaticObject() {
	  return tTransportStaticObject;
   }

   /**
	* Sets the value of the tTransportStaticObject property.
	*
	* @param value allowed object is
	*              {@link TTransportStaticObject }
	*/
   public void setTTransportStaticObject(TTransportStaticObject value) {
	  this.tTransportStaticObject = value;
   }

   /**
	* Gets the value of the tTransportStaticObjectType property.
	*
	* @return possible object is
	* {@link TTransportStaticObjectType }
	*/
   public TTransportStaticObjectType getTTransportStaticObjectType() {
	  return tTransportStaticObjectType;
   }

   /**
	* Sets the value of the tTransportStaticObjectType property.
	*
	* @param value allowed object is
	*              {@link TTransportStaticObjectType }
	*/
   public void setTTransportStaticObjectType(TTransportStaticObjectType value) {
	  this.tTransportStaticObjectType = value;
   }

   /**
	* Gets the value of the tCompensatoryRoute property.
	*
	* @return possible object is
	* {@link TCompensatoryRoute }
	*/
   public TCompensatoryRoute getTCompensatoryRoute() {
	  return tCompensatoryRoute;
   }

   /**
	* Sets the value of the tCompensatoryRoute property.
	*
	* @param value allowed object is
	*              {@link TCompensatoryRoute }
	*/
   public void setTCompensatoryRoute(TCompensatoryRoute value) {
	  this.tCompensatoryRoute = value;
   }

   /**
	* Gets the value of the tCompensatoryPoint property.
	*
	* @return possible object is
	* {@link TCompensatoryPoint }
	*/
   public TCompensatoryPoint getTCompensatoryPoint() {
	  return tCompensatoryPoint;
   }

   /**
	* Sets the value of the tCompensatoryPoint property.
	*
	* @param value allowed object is
	*              {@link TCompensatoryPoint }
	*/
   public void setTCompensatoryPoint(TCompensatoryPoint value) {
	  this.tCompensatoryPoint = value;
   }

   /**
	* Gets the value of the tCompensatoryPointType property.
	*
	* @return possible object is
	* {@link TCompensatoryPointType }
	*/
   public TCompensatoryPointType getTCompensatoryPointType() {
	  return tCompensatoryPointType;
   }

   /**
	* Sets the value of the tCompensatoryPointType property.
	*
	* @param value allowed object is
	*              {@link TCompensatoryPointType }
	*/
   public void setTCompensatoryPointType(TCompensatoryPointType value) {
	  this.tCompensatoryPointType = value;
   }

   /**
	* Gets the value of the tMovementDirection property.
	*
	* @return possible object is
	* {@link TMovementDirection }
	*/
   public TMovementDirection getTMovementDirection() {
	  return tMovementDirection;
   }

   /**
	* Sets the value of the tMovementDirection property.
	*
	* @param value allowed object is
	*              {@link TMovementDirection }
	*/
   public void setTMovementDirection(TMovementDirection value) {
	  this.tMovementDirection = value;
   }

   /**
	* Gets the value of the tRoadSurfaceType property.
	*
	* @return possible object is
	* {@link TRoadSurfaceType }
	*/
   public TRoadSurfaceType getTRoadSurfaceType() {
	  return tRoadSurfaceType;
   }

   /**
	* Sets the value of the tRoadSurfaceType property.
	*
	* @param value allowed object is
	*              {@link TRoadSurfaceType }
	*/
   public void setTRoadSurfaceType(TRoadSurfaceType value) {
	  this.tRoadSurfaceType = value;
   }

   /**
	* Gets the value of the tAgencyOrganizationForm property.
	*
	* @return possible object is
	* {@link TAgencyOrganizationForm }
	*/
   public TAgencyOrganizationForm getTAgencyOrganizationForm() {
	  return tAgencyOrganizationForm;
   }

   /**
	* Sets the value of the tAgencyOrganizationForm property.
	*
	* @param value allowed object is
	*              {@link TAgencyOrganizationForm }
	*/
   public void setTAgencyOrganizationForm(TAgencyOrganizationForm value) {
	  this.tAgencyOrganizationForm = value;
   }

}
