//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Заголовок сообщения жизненного цикла объектов системы
 * <p>
 * <p>Java class for msg_TObjectMessageHeader complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="msg_TObjectMessageHeader">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="messageIdent" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TMessageIdent"/>
 *         &lt;element name="operation" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TEventName"/>
 *         &lt;element name="objectType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TObjectType"/>
 *         &lt;element name="identSet" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComponentIds"/>
 *         &lt;element name="timestamp" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TMessageTimestamp"/>
 *         &lt;element name="priority" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TPriority"/>
 *         &lt;element name="targetList" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TMessageTargetList"/>
 *         &lt;element name="source" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TMessageSource"/>
 *         &lt;element name="security" type="{http://www.w3.org/2001/XMLSchema}anyType" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "msg_TObjectMessageHeader", propOrder = {
	"messageIdent",
	"operation",
	"objectType",
	"identSet",
	"timestamp",
	"priority",
	"targetList",
	"source",
	"security"
})
public class MsgTObjectMessageHeader {

   @XmlElement(required = true)
   protected String messageIdent;
   @XmlElement(required = true)
   protected MsgTEventName operation;
   @XmlElement(required = true)
   protected TObjectType objectType;
   @XmlElement(required = true)
   protected TComponentIds identSet;
   @XmlElement(required = true)
   protected XMLGregorianCalendar timestamp;
   @XmlElement(required = true)
   protected String priority;
   @XmlElement(required = true)
   protected MsgTMessageTargetList targetList;
   @XmlElement(required = true)
   protected String source;
   protected Object security;

   /**
	* Gets the value of the messageIdent property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getMessageIdent() {
	  return messageIdent;
   }

   /**
	* Sets the value of the messageIdent property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setMessageIdent(String value) {
	  this.messageIdent = value;
   }

   /**
	* Gets the value of the operation property.
	*
	* @return possible object is
	* {@link MsgTEventName }
	*/
   public MsgTEventName getOperation() {
	  return operation;
   }

   /**
	* Sets the value of the operation property.
	*
	* @param value allowed object is
	*              {@link MsgTEventName }
	*/
   public void setOperation(MsgTEventName value) {
	  this.operation = value;
   }

   /**
	* Gets the value of the objectType property.
	*
	* @return possible object is
	* {@link TObjectType }
	*/
   public TObjectType getObjectType() {
	  return objectType;
   }

   /**
	* Sets the value of the objectType property.
	*
	* @param value allowed object is
	*              {@link TObjectType }
	*/
   public void setObjectType(TObjectType value) {
	  this.objectType = value;
   }

   /**
	* Gets the value of the identSet property.
	*
	* @return possible object is
	* {@link TComponentIds }
	*/
   public TComponentIds getIdentSet() {
	  return identSet;
   }

   /**
	* Sets the value of the identSet property.
	*
	* @param value allowed object is
	*              {@link TComponentIds }
	*/
   public void setIdentSet(TComponentIds value) {
	  this.identSet = value;
   }

   /**
	* Gets the value of the timestamp property.
	*
	* @return possible object is
	* {@link XMLGregorianCalendar }
	*/
   public XMLGregorianCalendar getTimestamp() {
	  return timestamp;
   }

   /**
	* Sets the value of the timestamp property.
	*
	* @param value allowed object is
	*              {@link XMLGregorianCalendar }
	*/
   public void setTimestamp(XMLGregorianCalendar value) {
	  this.timestamp = value;
   }

   /**
	* Gets the value of the priority property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getPriority() {
	  return priority;
   }

   /**
	* Sets the value of the priority property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setPriority(String value) {
	  this.priority = value;
   }

   /**
	* Gets the value of the targetList property.
	*
	* @return possible object is
	* {@link MsgTMessageTargetList }
	*/
   public MsgTMessageTargetList getTargetList() {
	  return targetList;
   }

   /**
	* Sets the value of the targetList property.
	*
	* @param value allowed object is
	*              {@link MsgTMessageTargetList }
	*/
   public void setTargetList(MsgTMessageTargetList value) {
	  this.targetList = value;
   }

   /**
	* Gets the value of the source property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getSource() {
	  return source;
   }

   /**
	* Sets the value of the source property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setSource(String value) {
	  this.source = value;
   }

   /**
	* Gets the value of the security property.
	*
	* @return possible object is
	* {@link Object }
	*/
   public Object getSecurity() {
	  return security;
   }

   /**
	* Sets the value of the security property.
	*
	* @param value allowed object is
	*              {@link Object }
	*/
   public void setSecurity(Object value) {
	  this.security = value;
   }

}
