//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * Ответ целевых АС
 * <p>
 * <p>Java class for msg_TStatusMessage complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="msg_TStatusMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="message-ident" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TMessageIdent"/>
 *                   &lt;element name="status-for" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TMessageIdent"/>
 *                   &lt;element name="timestamp" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TMessageTimestamp"/>
 *                   &lt;element name="source" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComponentName"/>
 *                   &lt;element name="operation" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TEventName"/>
 *                   &lt;element name="objects" minOccurs="0">
 *                     &lt;complexType>
 *                       &lt;complexContent>
 *                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                           &lt;sequence>
 *                             &lt;element name="object" maxOccurs="unbounded">
 *                               &lt;complexType>
 *                                 &lt;complexContent>
 *                                   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                                     &lt;sequence>
 *                                       &lt;element name="objectType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TObjectType"/>
 *                                       &lt;element name="objectIds" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComponentIds"/>
 *                                     &lt;/sequence>
 *                                   &lt;/restriction>
 *                                 &lt;/complexContent>
 *                               &lt;/complexType>
 *                             &lt;/element>
 *                           &lt;/sequence>
 *                         &lt;/restriction>
 *                       &lt;/complexContent>
 *                     &lt;/complexType>
 *                   &lt;/element>
 *                   &lt;element name="status" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TOperationStatus"/>
 *                   &lt;element name="status-message" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TOperationStatusMessage"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "msg_TStatusMessage", propOrder = {
	"header"
})
@XmlRootElement(name = "status-message")
public class StatusMessage {

   @XmlElement(required = true)
   protected StatusMessage.Header header;

   /**
	* Gets the value of the header property.
	*
	* @return possible object is
	* {@link StatusMessage.Header }
	*/
   public StatusMessage.Header getHeader() {
	  return header;
   }

   /**
	* Sets the value of the header property.
	*
	* @param value allowed object is
	*              {@link StatusMessage.Header }
	*/
   public void setHeader(StatusMessage.Header value) {
	  this.header = value;
   }


   /**
	* <p>Java class for anonymous complex type.
	* <p>
	* <p>The following schema fragment specifies the expected content contained within this class.
	* <p>
	* <pre>
	* &lt;complexType>
	*   &lt;complexContent>
	*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	*       &lt;sequence>
	*         &lt;element name="message-ident" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TMessageIdent"/>
	*         &lt;element name="status-for" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TMessageIdent"/>
	*         &lt;element name="timestamp" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TMessageTimestamp"/>
	*         &lt;element name="source" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComponentName"/>
	*         &lt;element name="operation" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TEventName"/>
	*         &lt;element name="objects" minOccurs="0">
	*           &lt;complexType>
	*             &lt;complexContent>
	*               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	*                 &lt;sequence>
	*                   &lt;element name="object" maxOccurs="unbounded">
	*                     &lt;complexType>
	*                       &lt;complexContent>
	*                         &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	*                           &lt;sequence>
	*                             &lt;element name="objectType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TObjectType"/>
	*                             &lt;element name="objectIds" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComponentIds"/>
	*                           &lt;/sequence>
	*                         &lt;/restriction>
	*                       &lt;/complexContent>
	*                     &lt;/complexType>
	*                   &lt;/element>
	*                 &lt;/sequence>
	*               &lt;/restriction>
	*             &lt;/complexContent>
	*           &lt;/complexType>
	*         &lt;/element>
	*         &lt;element name="status" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TOperationStatus"/>
	*         &lt;element name="status-message" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TOperationStatusMessage"/>
	*       &lt;/sequence>
	*     &lt;/restriction>
	*   &lt;/complexContent>
	* &lt;/complexType>
	* </pre>
	*/
   @XmlAccessorType(XmlAccessType.FIELD)
   @XmlType(name = "", propOrder = {
	   "messageIdent",
	   "statusFor",
	   "timestamp",
	   "source",
	   "operation",
	   "objects",
	   "status",
	   "statusMessage"
   })
   public static class Header {

	  @XmlElement(name = "message-ident", required = true)
	  protected String messageIdent;
	  @XmlElement(name = "status-for", required = true)
	  protected String statusFor;
	  @XmlElement(required = true)
	  protected XMLGregorianCalendar timestamp;
	  @XmlElement(required = true)
	  protected String source;
	  @XmlElement(required = true)
	  protected MsgTEventName operation;
	  protected StatusMessage.Header.Objects objects;
	  @XmlElement(required = true)
	  protected BigInteger status;
	  @XmlElement(name = "status-message", required = true)
	  protected String statusMessage;

	  /**
	   * Gets the value of the messageIdent property.
	   *
	   * @return possible object is
	   * {@link String }
	   */
	  public String getMessageIdent() {
		 return messageIdent;
	  }

	  /**
	   * Sets the value of the messageIdent property.
	   *
	   * @param value allowed object is
	   *              {@link String }
	   */
	  public void setMessageIdent(String value) {
		 this.messageIdent = value;
	  }

	  /**
	   * Gets the value of the statusFor property.
	   *
	   * @return possible object is
	   * {@link String }
	   */
	  public String getStatusFor() {
		 return statusFor;
	  }

	  /**
	   * Sets the value of the statusFor property.
	   *
	   * @param value allowed object is
	   *              {@link String }
	   */
	  public void setStatusFor(String value) {
		 this.statusFor = value;
	  }

	  /**
	   * Gets the value of the timestamp property.
	   *
	   * @return possible object is
	   * {@link XMLGregorianCalendar }
	   */
	  public XMLGregorianCalendar getTimestamp() {
		 return timestamp;
	  }

	  /**
	   * Sets the value of the timestamp property.
	   *
	   * @param value allowed object is
	   *              {@link XMLGregorianCalendar }
	   */
	  public void setTimestamp(XMLGregorianCalendar value) {
		 this.timestamp = value;
	  }

	  /**
	   * Gets the value of the source property.
	   *
	   * @return possible object is
	   * {@link String }
	   */
	  public String getSource() {
		 return source;
	  }

	  /**
	   * Sets the value of the source property.
	   *
	   * @param value allowed object is
	   *              {@link String }
	   */
	  public void setSource(String value) {
		 this.source = value;
	  }

	  /**
	   * Gets the value of the operation property.
	   *
	   * @return possible object is
	   * {@link MsgTEventName }
	   */
	  public MsgTEventName getOperation() {
		 return operation;
	  }

	  /**
	   * Sets the value of the operation property.
	   *
	   * @param value allowed object is
	   *              {@link MsgTEventName }
	   */
	  public void setOperation(MsgTEventName value) {
		 this.operation = value;
	  }

	  /**
	   * Gets the value of the objects property.
	   *
	   * @return possible object is
	   * {@link StatusMessage.Header.Objects }
	   */
	  public StatusMessage.Header.Objects getObjects() {
		 return objects;
	  }

	  /**
	   * Sets the value of the objects property.
	   *
	   * @param value allowed object is
	   *              {@link StatusMessage.Header.Objects }
	   */
	  public void setObjects(StatusMessage.Header.Objects value) {
		 this.objects = value;
	  }

	  /**
	   * Gets the value of the status property.
	   *
	   * @return possible object is
	   * {@link BigInteger }
	   */
	  public BigInteger getStatus() {
		 return status;
	  }

	  /**
	   * Sets the value of the status property.
	   *
	   * @param value allowed object is
	   *              {@link BigInteger }
	   */
	  public void setStatus(BigInteger value) {
		 this.status = value;
	  }

	  /**
	   * Gets the value of the statusMessage property.
	   *
	   * @return possible object is
	   * {@link String }
	   */
	  public String getStatusMessage() {
		 return statusMessage;
	  }

	  /**
	   * Sets the value of the statusMessage property.
	   *
	   * @param value allowed object is
	   *              {@link String }
	   */
	  public void setStatusMessage(String value) {
		 this.statusMessage = value;
	  }


	  /**
	   * <p>Java class for anonymous complex type.
	   * <p>
	   * <p>The following schema fragment specifies the expected content contained within this class.
	   * <p>
	   * <pre>
	   * &lt;complexType>
	   *   &lt;complexContent>
	   *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	   *       &lt;sequence>
	   *         &lt;element name="object" maxOccurs="unbounded">
	   *           &lt;complexType>
	   *             &lt;complexContent>
	   *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	   *                 &lt;sequence>
	   *                   &lt;element name="objectType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TObjectType"/>
	   *                   &lt;element name="objectIds" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComponentIds"/>
	   *                 &lt;/sequence>
	   *               &lt;/restriction>
	   *             &lt;/complexContent>
	   *           &lt;/complexType>
	   *         &lt;/element>
	   *       &lt;/sequence>
	   *     &lt;/restriction>
	   *   &lt;/complexContent>
	   * &lt;/complexType>
	   * </pre>
	   */
	  @XmlAccessorType(XmlAccessType.FIELD)
	  @XmlType(name = "", propOrder = {
		  "objects"
	  })
	  public static class Objects {

		 @XmlElement(name = "object", required = true)
		 protected List<StatusMessage.Header.Objects.Object> objects;

		 /**
		  * Gets the value of the objects property.
		  * <p>
		  * <p>
		  * This accessor method returns a reference to the live list,
		  * not a snapshot. Therefore any modification you make to the
		  * returned list will be present inside the JAXB object.
		  * This is why there is not a <CODE>set</CODE> method for the objects property.
		  * <p>
		  * <p>
		  * For example, to add a new item, do as follows:
		  * <pre>
		  *    getObjects().add(newItem);
		  * </pre>
		  * <p>
		  * <p>
		  * <p>
		  * Objects of the following type(s) are allowed in the list
		  * {@link StatusMessage.Header.Objects.Object }
		  */
		 public List<StatusMessage.Header.Objects.Object> getObjects() {
			if (objects == null) {
			   objects = new ArrayList<StatusMessage.Header.Objects.Object>();
			}
			return this.objects;
		 }


		 /**
		  * <p>Java class for anonymous complex type.
		  * <p>
		  * <p>The following schema fragment specifies the expected content contained within this class.
		  * <p>
		  * <pre>
		  * &lt;complexType>
		  *   &lt;complexContent>
		  *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
		  *       &lt;sequence>
		  *         &lt;element name="objectType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TObjectType"/>
		  *         &lt;element name="objectIds" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComponentIds"/>
		  *       &lt;/sequence>
		  *     &lt;/restriction>
		  *   &lt;/complexContent>
		  * &lt;/complexType>
		  * </pre>
		  */
		 @XmlAccessorType(XmlAccessType.FIELD)
		 @XmlType(name = "", propOrder = {
			 "objectType",
			 "objectIds"
		 })
		 public static class Object {

			@XmlElement(required = true)
			protected TObjectType objectType;
			@XmlElement(required = true)
			protected TComponentIds objectIds;

			/**
			 * Gets the value of the objectType property.
			 *
			 * @return possible object is
			 * {@link TObjectType }
			 */
			public TObjectType getObjectType() {
			   return objectType;
			}

			/**
			 * Sets the value of the objectType property.
			 *
			 * @param value allowed object is
			 *              {@link TObjectType }
			 */
			public void setObjectType(TObjectType value) {
			   this.objectType = value;
			}

			/**
			 * Gets the value of the objectIds property.
			 *
			 * @return possible object is
			 * {@link TComponentIds }
			 */
			public TComponentIds getObjectIds() {
			   return objectIds;
			}

			/**
			 * Sets the value of the objectIds property.
			 *
			 * @param value allowed object is
			 *              {@link TComponentIds }
			 */
			public void setObjectIds(TComponentIds value) {
			   this.objectIds = value;
			}

		 }

	  }

   }

}
