//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;
import java.util.ArrayList;
import java.util.List;


/**
 * Список компонентозависимых идентификаторов
 * <p>
 * <p>Java class for TComponentIds complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TComponentIds">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="componentId" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComponentId" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TComponentIds", propOrder = {
	"componentIds"
})
public class TComponentIds {

   @XmlElement(name = "componentId", required = true)
   protected List<TComponentId> componentIds;

   /**
	* Gets the value of the componentIds property.
	* <p>
	* <p>
	* This accessor method returns a reference to the live list,
	* not a snapshot. Therefore any modification you make to the
	* returned list will be present inside the JAXB object.
	* This is why there is not a <CODE>set</CODE> method for the componentIds property.
	* <p>
	* <p>
	* For example, to add a new item, do as follows:
	* <pre>
	*    getComponentIds().add(newItem);
	* </pre>
	* <p>
	* <p>
	* <p>
	* Objects of the following type(s) are allowed in the list
	* {@link TComponentId }
	*/
   public List<TComponentId> getComponentIds() {
	  if (componentIds == null) {
		 componentIds = new ArrayList<TComponentId>();
	  }
	  return this.componentIds;
   }

}
