//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;


/**
 * Компонентозависимый идентификатор
 * <p>
 * <p>Java class for TComponentId complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TComponentId">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="component" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComponentName"/>
 *         &lt;element name="componentIdent" type="{http://www.w3.org/2001/XMLSchema}string" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TComponentId", propOrder = {
	"component",
	"componentIdent"
})
public class TComponentId {

   @XmlElement(required = true)
   protected String component;
   @XmlElementRef(name = "componentIdent", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> componentIdent;

   /**
	* Gets the value of the component property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getComponent() {
	  return component;
   }

   /**
	* Sets the value of the component property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setComponent(String value) {
	  this.component = value;
   }

   /**
	* Gets the value of the componentIdent property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getComponentIdent() {
	  return componentIdent;
   }

   /**
	* Sets the value of the componentIdent property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setComponentIdent(JAXBElement<String> value) {
	  this.componentIdent = value;
   }

}
