//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * Дуги графа
 * <p>
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;tags xmlns="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:gismgt="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:p578540_="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:p729618_="http://java.sun.com/xml/ns/jaxb" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;&lt;tag&gt;mtrans&lt;/tag&gt;&lt;/tags&gt;
 * </pre>
 * <p>
 * <p>
 * <p>Java class for TGraphSection complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TGraphSection">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://mappl.ru/2015/XMLSchema/GISMGT}TGISDictionaryObject"/>
 *         &lt;element name="startNode" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RGraphNode" minOccurs="0"/>
 *         &lt;element name="endNode" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RGraphNode" minOccurs="0"/>
 *         &lt;element name="surfaceType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRoadSurfaceType" minOccurs="0"/>
 *         &lt;element name="hasBus" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSign" minOccurs="0"/>
 *         &lt;element name="hasTrolley" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSign" minOccurs="0"/>
 *         &lt;element name="hasTram" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSign" minOccurs="0"/>
 *         &lt;element name="hasSpeedTram" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSign" minOccurs="0"/>
 *         &lt;element name="hasRoutes" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSign" minOccurs="0"/>
 *         &lt;element name="hasNulls" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSign" minOccurs="0"/>
 *         &lt;element name="hasBusLane" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSign" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TGraphSection", propOrder = {
	"muid",
	"version",
	"signDeleted",
	"wktGeom",
	"startNode",
	"endNode",
	"surfaceType",
	"hasBus",
	"hasTrolley",
	"hasTram",
	"hasSpeedTram",
	"hasRoutes",
	"hasNulls",
	"hasBusLane"
})
public class TGraphSection {

   @XmlElement(required = true)
   protected String muid;
   @XmlElement(defaultValue = "1")
   protected BigInteger version;
   @XmlElementRef(name = "signDeleted", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> signDeleted;
   @XmlElementRef(name = "wkt_geom", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> wktGeom;
   @XmlElementRef(name = "startNode", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RGraphNode> startNode;
   @XmlElementRef(name = "endNode", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RGraphNode> endNode;
   @XmlElementRef(name = "surfaceType", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RRoadSurfaceType> surfaceType;
   @XmlElementRef(name = "hasBus", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasBus;
   @XmlElementRef(name = "hasTrolley", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasTrolley;
   @XmlElementRef(name = "hasTram", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasTram;
   @XmlElementRef(name = "hasSpeedTram", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasSpeedTram;
   @XmlElementRef(name = "hasRoutes", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasRoutes;
   @XmlElementRef(name = "hasNulls", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasNulls;
   @XmlElementRef(name = "hasBusLane", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasBusLane;

   /**
	* Gets the value of the muid property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getMuid() {
	  return muid;
   }

   /**
	* Sets the value of the muid property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setMuid(String value) {
	  this.muid = value;
   }

   /**
	* Gets the value of the version property.
	*
	* @return possible object is
	* {@link BigInteger }
	*/
   public BigInteger getVersion() {
	  return version;
   }

   /**
	* Sets the value of the version property.
	*
	* @param value allowed object is
	*              {@link BigInteger }
	*/
   public void setVersion(BigInteger value) {
	  this.version = value;
   }

   /**
	* Gets the value of the signDeleted property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getSignDeleted() {
	  return signDeleted;
   }

   /**
	* Sets the value of the signDeleted property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setSignDeleted(JAXBElement<BigInteger> value) {
	  this.signDeleted = value;
   }

   /**
	* Gets the value of the wktGeom property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getWktGeom() {
	  return wktGeom;
   }

   /**
	* Sets the value of the wktGeom property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setWktGeom(JAXBElement<String> value) {
	  this.wktGeom = value;
   }

   /**
	* Gets the value of the startNode property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RGraphNode }{@code >}
	*/
   public JAXBElement<RGraphNode> getStartNode() {
	  return startNode;
   }

   /**
	* Sets the value of the startNode property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RGraphNode }{@code >}
	*/
   public void setStartNode(JAXBElement<RGraphNode> value) {
	  this.startNode = value;
   }

   /**
	* Gets the value of the endNode property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RGraphNode }{@code >}
	*/
   public JAXBElement<RGraphNode> getEndNode() {
	  return endNode;
   }

   /**
	* Sets the value of the endNode property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RGraphNode }{@code >}
	*/
   public void setEndNode(JAXBElement<RGraphNode> value) {
	  this.endNode = value;
   }

   /**
	* Gets the value of the surfaceType property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RRoadSurfaceType }{@code >}
	*/
   public JAXBElement<RRoadSurfaceType> getSurfaceType() {
	  return surfaceType;
   }

   /**
	* Sets the value of the surfaceType property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RRoadSurfaceType }{@code >}
	*/
   public void setSurfaceType(JAXBElement<RRoadSurfaceType> value) {
	  this.surfaceType = value;
   }

   /**
	* Gets the value of the hasBus property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasBus() {
	  return hasBus;
   }

   /**
	* Sets the value of the hasBus property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasBus(JAXBElement<BigInteger> value) {
	  this.hasBus = value;
   }

   /**
	* Gets the value of the hasTrolley property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasTrolley() {
	  return hasTrolley;
   }

   /**
	* Sets the value of the hasTrolley property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasTrolley(JAXBElement<BigInteger> value) {
	  this.hasTrolley = value;
   }

   /**
	* Gets the value of the hasTram property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasTram() {
	  return hasTram;
   }

   /**
	* Sets the value of the hasTram property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasTram(JAXBElement<BigInteger> value) {
	  this.hasTram = value;
   }

   /**
	* Gets the value of the hasSpeedTram property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasSpeedTram() {
	  return hasSpeedTram;
   }

   /**
	* Sets the value of the hasSpeedTram property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasSpeedTram(JAXBElement<BigInteger> value) {
	  this.hasSpeedTram = value;
   }

   /**
	* Gets the value of the hasRoutes property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasRoutes() {
	  return hasRoutes;
   }

   /**
	* Sets the value of the hasRoutes property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasRoutes(JAXBElement<BigInteger> value) {
	  this.hasRoutes = value;
   }

   /**
	* Gets the value of the hasNulls property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasNulls() {
	  return hasNulls;
   }

   /**
	* Sets the value of the hasNulls property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasNulls(JAXBElement<BigInteger> value) {
	  this.hasNulls = value;
   }

   /**
	* Gets the value of the hasBusLane property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasBusLane() {
	  return hasBusLane;
   }

   /**
	* Sets the value of the hasBusLane property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasBusLane(JAXBElement<BigInteger> value) {
	  this.hasBusLane = value;
   }

}
