//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.annotation.XmlEnum;
import javax.xml.bind.annotation.XmlEnumValue;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for TObjectType.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;simpleType name="TObjectType">
 *   &lt;restriction base="{http://www.w3.org/2001/XMLSchema}string">
 *     &lt;enumeration value="TAgencyOrganizationForm"/>
 *     &lt;enumeration value="TRoadSurfaceType"/>
 *     &lt;enumeration value="TMovementDirection"/>
 *     &lt;enumeration value="TCompensatoryPointType"/>
 *     &lt;enumeration value="TCompensatoryPoint"/>
 *     &lt;enumeration value="TCompensatoryRoute"/>
 *     &lt;enumeration value="TTransportStaticObjectType"/>
 *     &lt;enumeration value="TTransportStaticObject"/>
 *     &lt;enumeration value="TTicketSalePoint"/>
 *     &lt;enumeration value="TOrderKind"/>
 *     &lt;enumeration value="TOrderType"/>
 *     &lt;enumeration value="TRouteKind"/>
 *     &lt;enumeration value="TRouteState"/>
 *     &lt;enumeration value="TRouteState2"/>
 *     &lt;enumeration value="TRouteTransportKind"/>
 *     &lt;enumeration value="TRouteTransportationKind"/>
 *     &lt;enumeration value="TRouteTrajectoryType"/>
 *     &lt;enumeration value="TRouteVariantType"/>
 *     &lt;enumeration value="TRouteRoundType"/>
 *     &lt;enumeration value="TRouteNullRoundType"/>
 *     &lt;enumeration value="TRouteRound"/>
 *     &lt;enumeration value="TRouteNullRound"/>
 *     &lt;enumeration value="TStopMode"/>
 *     &lt;enumeration value="TStopState"/>
 *     &lt;enumeration value="TStopType"/>
 *     &lt;enumeration value="TTransportKind"/>
 *     &lt;enumeration value="TVehicleType"/>
 *     &lt;enumeration value="TBuilding"/>
 *     &lt;enumeration value="TStreet"/>
 *     &lt;enumeration value="TDistrict"/>
 *     &lt;enumeration value="TRegion"/>
 *     &lt;enumeration value="TEGKODistrict"/>
 *     &lt;enumeration value="TEGKORegion"/>
 *     &lt;enumeration value="TAgency"/>
 *     &lt;enumeration value="TGraphNode"/>
 *     &lt;enumeration value="TGraphSection"/>
 *     &lt;enumeration value="TOrder"/>
 *     &lt;enumeration value="TPark"/>
 *     &lt;enumeration value="TParkZone"/>
 *     &lt;enumeration value="TRouteTrajectory"/>
 *     &lt;enumeration value="TRouteVariant"/>
 *     &lt;enumeration value="TRoute"/>
 *     &lt;enumeration value="TStopPlace"/>
 *     &lt;enumeration value="TStopZone"/>
 *     &lt;enumeration value="TStop"/>
 *     &lt;enumeration value="TTerminalStation"/>
 *     &lt;enumeration value="TTransportParking"/>
 *     &lt;enumeration value="TTerminalPointZone"/>
 *     &lt;enumeration value="TRouteTrajectories2StopPlaces"/>
 *     &lt;enumeration value="TRouteTrajectories2GraphSections"/>
 *     &lt;enumeration value="TParks2Routes"/>
 *     &lt;enumeration value="TParks2VehicleTypes"/>
 *     &lt;enumeration value="TParks2Agencies"/>
 *     &lt;enumeration value="TStopPavilion"/>
 *     &lt;enumeration value="TStopPavilionInstallation"/>
 *     &lt;enumeration value="TStopPavilionOrder"/>
 *     &lt;enumeration value="TStopPavilionOrderType"/>
 *     &lt;enumeration value="TStopPavilionType"/>
 *     &lt;enumeration value="TStopPavilionState"/>
 *     &lt;enumeration value="TStopPavilionBalanceOrganization"/>
 *     &lt;enumeration value="TStopPavilionInstallOrganization"/>
 *     &lt;enumeration value="TStopPavilionServiceOrganization"/>
 *   &lt;/restriction>
 * &lt;/simpleType>
 * </pre>
 */
@XmlType(name = "TObjectType")
@XmlEnum
public enum TObjectType {

   @XmlEnumValue("TAgencyOrganizationForm")
   T_AGENCY_ORGANIZATION_FORM("TAgencyOrganizationForm"),
   @XmlEnumValue("TRoadSurfaceType")
   T_ROAD_SURFACE_TYPE("TRoadSurfaceType"),
   @XmlEnumValue("TMovementDirection")
   T_MOVEMENT_DIRECTION("TMovementDirection"),
   @XmlEnumValue("TCompensatoryPointType")
   T_COMPENSATORY_POINT_TYPE("TCompensatoryPointType"),
   @XmlEnumValue("TCompensatoryPoint")
   T_COMPENSATORY_POINT("TCompensatoryPoint"),
   @XmlEnumValue("TCompensatoryRoute")
   T_COMPENSATORY_ROUTE("TCompensatoryRoute"),
   @XmlEnumValue("TTransportStaticObjectType")
   T_TRANSPORT_STATIC_OBJECT_TYPE("TTransportStaticObjectType"),
   @XmlEnumValue("TTransportStaticObject")
   T_TRANSPORT_STATIC_OBJECT("TTransportStaticObject"),
   @XmlEnumValue("TTicketSalePoint")
   T_TICKET_SALE_POINT("TTicketSalePoint"),
   @XmlEnumValue("TOrderKind")
   T_ORDER_KIND("TOrderKind"),
   @XmlEnumValue("TOrderType")
   T_ORDER_TYPE("TOrderType"),
   @XmlEnumValue("TRouteKind")
   T_ROUTE_KIND("TRouteKind"),
   @XmlEnumValue("TRouteState")
   T_ROUTE_STATE("TRouteState"),
   @XmlEnumValue("TRouteState2")
   T_ROUTE_STATE_2("TRouteState2"),
   @XmlEnumValue("TRouteTransportKind")
   T_ROUTE_TRANSPORT_KIND("TRouteTransportKind"),
   @XmlEnumValue("TRouteTransportationKind")
   T_ROUTE_TRANSPORTATION_KIND("TRouteTransportationKind"),
   @XmlEnumValue("TRouteTrajectoryType")
   T_ROUTE_TRAJECTORY_TYPE("TRouteTrajectoryType"),
   @XmlEnumValue("TRouteVariantType")
   T_ROUTE_VARIANT_TYPE("TRouteVariantType"),
   @XmlEnumValue("TRouteRoundType")
   T_ROUTE_ROUND_TYPE("TRouteRoundType"),
   @XmlEnumValue("TRouteNullRoundType")
   T_ROUTE_NULL_ROUND_TYPE("TRouteNullRoundType"),
   @XmlEnumValue("TRouteRound")
   T_ROUTE_ROUND("TRouteRound"),
   @XmlEnumValue("TRouteNullRound")
   T_ROUTE_NULL_ROUND("TRouteNullRound"),
   @XmlEnumValue("TStopMode")
   T_STOP_MODE("TStopMode"),
   @XmlEnumValue("TStopState")
   T_STOP_STATE("TStopState"),
   @XmlEnumValue("TStopType")
   T_STOP_TYPE("TStopType"),
   @XmlEnumValue("TTransportKind")
   T_TRANSPORT_KIND("TTransportKind"),
   @XmlEnumValue("TVehicleType")
   T_VEHICLE_TYPE("TVehicleType"),
   @XmlEnumValue("TBuilding")
   T_BUILDING("TBuilding"),
   @XmlEnumValue("TStreet")
   T_STREET("TStreet"),
   @XmlEnumValue("TDistrict")
   T_DISTRICT("TDistrict"),
   @XmlEnumValue("TRegion")
   T_REGION("TRegion"),
   @XmlEnumValue("TEGKODistrict")
   TEGKO_DISTRICT("TEGKODistrict"),
   @XmlEnumValue("TEGKORegion")
   TEGKO_REGION("TEGKORegion"),
   @XmlEnumValue("TAgency")
   T_AGENCY("TAgency"),
   @XmlEnumValue("TGraphNode")
   T_GRAPH_NODE("TGraphNode"),
   @XmlEnumValue("TGraphSection")
   T_GRAPH_SECTION("TGraphSection"),
   @XmlEnumValue("TOrder")
   T_ORDER("TOrder"),
   @XmlEnumValue("TPark")
   T_PARK("TPark"),
   @XmlEnumValue("TParkZone")
   T_PARK_ZONE("TParkZone"),
   @XmlEnumValue("TRouteTrajectory")
   T_ROUTE_TRAJECTORY("TRouteTrajectory"),
   @XmlEnumValue("TRouteVariant")
   T_ROUTE_VARIANT("TRouteVariant"),
   @XmlEnumValue("TRoute")
   T_ROUTE("TRoute"),
   @XmlEnumValue("TStopPlace")
   T_STOP_PLACE("TStopPlace"),
   @XmlEnumValue("TStopZone")
   T_STOP_ZONE("TStopZone"),
   @XmlEnumValue("TStop")
   T_STOP("TStop"),
   @XmlEnumValue("TTerminalStation")
   T_TERMINAL_STATION("TTerminalStation"),
   @XmlEnumValue("TTransportParking")
   T_TRANSPORT_PARKING("TTransportParking"),
   @XmlEnumValue("TTerminalPointZone")
   T_TERMINAL_POINT_ZONE("TTerminalPointZone"),
   @XmlEnumValue("TRouteTrajectories2StopPlaces")
   T_ROUTE_TRAJECTORIES_2_STOP_PLACES("TRouteTrajectories2StopPlaces"),
   @XmlEnumValue("TRouteTrajectories2GraphSections")
   T_ROUTE_TRAJECTORIES_2_GRAPH_SECTIONS("TRouteTrajectories2GraphSections"),
   @XmlEnumValue("TParks2Routes")
   T_PARKS_2_ROUTES("TParks2Routes"),
   @XmlEnumValue("TParks2VehicleTypes")
   T_PARKS_2_VEHICLE_TYPES("TParks2VehicleTypes"),
   @XmlEnumValue("TParks2Agencies")
   T_PARKS_2_AGENCIES("TParks2Agencies"),
   @XmlEnumValue("TStopPavilion")
   T_STOP_PAVILION("TStopPavilion"),
   @XmlEnumValue("TStopPavilionInstallation")
   T_STOP_PAVILION_INSTALLATION("TStopPavilionInstallation"),
   @XmlEnumValue("TStopPavilionOrder")
   T_STOP_PAVILION_ORDER("TStopPavilionOrder"),
   @XmlEnumValue("TStopPavilionOrderType")
   T_STOP_PAVILION_ORDER_TYPE("TStopPavilionOrderType"),
   @XmlEnumValue("TStopPavilionType")
   T_STOP_PAVILION_TYPE("TStopPavilionType"),
   @XmlEnumValue("TStopPavilionState")
   T_STOP_PAVILION_STATE("TStopPavilionState"),
   @XmlEnumValue("TStopPavilionBalanceOrganization")
   T_STOP_PAVILION_BALANCE_ORGANIZATION("TStopPavilionBalanceOrganization"),
   @XmlEnumValue("TStopPavilionInstallOrganization")
   T_STOP_PAVILION_INSTALL_ORGANIZATION("TStopPavilionInstallOrganization"),
   @XmlEnumValue("TStopPavilionServiceOrganization")
   T_STOP_PAVILION_SERVICE_ORGANIZATION("TStopPavilionServiceOrganization");
   private final String value;

   TObjectType(String v) {
	  value = v;
   }

   public String value() {
	  return value;
   }

   public static TObjectType fromValue(String v) {
	  for (TObjectType c : TObjectType.values()) {
		 if (c.value.equals(v)) {
			return c;
		 }
	  }
	  throw new IllegalArgumentException(v);
   }

}
