//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlType;


/**
 * Базовый объект компоненты
 * <p>
 * <p>Java class for TObject complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TObject">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element name="componentIds" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComponentIds"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TObject", propOrder = {
	"componentIds"
})
public class TObject {

   @XmlElement(required = true)
   protected TComponentIds componentIds;

   /**
	* Gets the value of the componentIds property.
	*
	* @return possible object is
	* {@link TComponentIds }
	*/
   public TComponentIds getComponentIds() {
	  return componentIds;
   }

   /**
	* Sets the value of the componentIds property.
	*
	* @param value allowed object is
	*              {@link TComponentIds }
	*/
   public void setComponentIds(TComponentIds value) {
	  this.componentIds = value;
   }

}
