//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * Автотранспортные предприятия / Парки
 * <p>
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;tags xmlns="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:gismgt="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:p578540_="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:p729618_="http://java.sun.com/xml/ns/jaxb" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;&lt;tag&gt;mtrans&lt;/tag&gt;&lt;/tags&gt;
 * </pre>
 * <p>
 * <p>
 * <p>Java class for TPark complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TPark">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://mappl.ru/2015/XMLSchema/GISMGT}TGISDictionaryObject"/>
 *         &lt;element name="agencies" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="agency" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RAgency" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="routes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="route" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRoute" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="vehicleTypes" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="vehicleType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RVehicleType" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="name" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TName" minOccurs="0"/>
 *         &lt;element name="shortName" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TName" minOccurs="0"/>
 *         &lt;element name="number" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TParkNumber" minOccurs="0"/>
 *         &lt;element name="routeTransportKind" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRouteTransportKind" minOccurs="0"/>
 *         &lt;element name="building" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RBuilding" minOccurs="0"/>
 *         &lt;element name="addressString" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TAddressString" minOccurs="0"/>
 *         &lt;element name="phone" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TPhone" minOccurs="0"/>
 *         &lt;element name="graphSection" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RGraphSection" minOccurs="0"/>
 *         &lt;element name="graphSectionOffset" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TLength" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TPark", propOrder = {
	"muid",
	"version",
	"signDeleted",
	"wktGeom",
	"agencies",
	"routes",
	"vehicleTypes",
	"name",
	"shortName",
	"number",
	"routeTransportKind",
	"building",
	"addressString",
	"phone",
	"graphSection",
	"graphSectionOffset"
})
public class TPark {

   @XmlElement(required = true)
   protected String muid;
   @XmlElement(defaultValue = "1")
   protected BigInteger version;
   @XmlElementRef(name = "signDeleted", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> signDeleted;
   @XmlElementRef(name = "wkt_geom", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> wktGeom;
   protected TPark.Agencies agencies;
   protected TPark.Routes routes;
   protected TPark.VehicleTypes vehicleTypes;
   @XmlElementRef(name = "name", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> name;
   @XmlElementRef(name = "shortName", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> shortName;
   @XmlElementRef(name = "number", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> number;
   @XmlElementRef(name = "routeTransportKind", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RRouteTransportKind> routeTransportKind;
   @XmlElementRef(name = "building", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RBuilding> building;
   @XmlElementRef(name = "addressString", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> addressString;
   @XmlElementRef(name = "phone", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> phone;
   @XmlElementRef(name = "graphSection", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RGraphSection> graphSection;
   @XmlElementRef(name = "graphSectionOffset", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Float> graphSectionOffset;

   /**
	* Gets the value of the muid property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getMuid() {
	  return muid;
   }

   /**
	* Sets the value of the muid property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setMuid(String value) {
	  this.muid = value;
   }

   /**
	* Gets the value of the version property.
	*
	* @return possible object is
	* {@link BigInteger }
	*/
   public BigInteger getVersion() {
	  return version;
   }

   /**
	* Sets the value of the version property.
	*
	* @param value allowed object is
	*              {@link BigInteger }
	*/
   public void setVersion(BigInteger value) {
	  this.version = value;
   }

   /**
	* Gets the value of the signDeleted property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getSignDeleted() {
	  return signDeleted;
   }

   /**
	* Sets the value of the signDeleted property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setSignDeleted(JAXBElement<BigInteger> value) {
	  this.signDeleted = value;
   }

   /**
	* Gets the value of the wktGeom property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getWktGeom() {
	  return wktGeom;
   }

   /**
	* Sets the value of the wktGeom property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setWktGeom(JAXBElement<String> value) {
	  this.wktGeom = value;
   }

   /**
	* Gets the value of the agencies property.
	*
	* @return possible object is
	* {@link TPark.Agencies }
	*/
   public TPark.Agencies getAgencies() {
	  return agencies;
   }

   /**
	* Sets the value of the agencies property.
	*
	* @param value allowed object is
	*              {@link TPark.Agencies }
	*/
   public void setAgencies(TPark.Agencies value) {
	  this.agencies = value;
   }

   /**
	* Gets the value of the routes property.
	*
	* @return possible object is
	* {@link TPark.Routes }
	*/
   public TPark.Routes getRoutes() {
	  return routes;
   }

   /**
	* Sets the value of the routes property.
	*
	* @param value allowed object is
	*              {@link TPark.Routes }
	*/
   public void setRoutes(TPark.Routes value) {
	  this.routes = value;
   }

   /**
	* Gets the value of the vehicleTypes property.
	*
	* @return possible object is
	* {@link TPark.VehicleTypes }
	*/
   public TPark.VehicleTypes getVehicleTypes() {
	  return vehicleTypes;
   }

   /**
	* Sets the value of the vehicleTypes property.
	*
	* @param value allowed object is
	*              {@link TPark.VehicleTypes }
	*/
   public void setVehicleTypes(TPark.VehicleTypes value) {
	  this.vehicleTypes = value;
   }

   /**
	* Gets the value of the name property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getName() {
	  return name;
   }

   /**
	* Sets the value of the name property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setName(JAXBElement<String> value) {
	  this.name = value;
   }

   /**
	* Gets the value of the shortName property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getShortName() {
	  return shortName;
   }

   /**
	* Sets the value of the shortName property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setShortName(JAXBElement<String> value) {
	  this.shortName = value;
   }

   /**
	* Gets the value of the number property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getNumber() {
	  return number;
   }

   /**
	* Sets the value of the number property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setNumber(JAXBElement<BigInteger> value) {
	  this.number = value;
   }

   /**
	* Gets the value of the routeTransportKind property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RRouteTransportKind }{@code >}
	*/
   public JAXBElement<RRouteTransportKind> getRouteTransportKind() {
	  return routeTransportKind;
   }

   /**
	* Sets the value of the routeTransportKind property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RRouteTransportKind }{@code >}
	*/
   public void setRouteTransportKind(JAXBElement<RRouteTransportKind> value) {
	  this.routeTransportKind = value;
   }

   /**
	* Gets the value of the building property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RBuilding }{@code >}
	*/
   public JAXBElement<RBuilding> getBuilding() {
	  return building;
   }

   /**
	* Sets the value of the building property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RBuilding }{@code >}
	*/
   public void setBuilding(JAXBElement<RBuilding> value) {
	  this.building = value;
   }

   /**
	* Gets the value of the addressString property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getAddressString() {
	  return addressString;
   }

   /**
	* Sets the value of the addressString property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setAddressString(JAXBElement<String> value) {
	  this.addressString = value;
   }

   /**
	* Gets the value of the phone property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getPhone() {
	  return phone;
   }

   /**
	* Sets the value of the phone property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setPhone(JAXBElement<String> value) {
	  this.phone = value;
   }

   /**
	* Gets the value of the graphSection property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RGraphSection }{@code >}
	*/
   public JAXBElement<RGraphSection> getGraphSection() {
	  return graphSection;
   }

   /**
	* Sets the value of the graphSection property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RGraphSection }{@code >}
	*/
   public void setGraphSection(JAXBElement<RGraphSection> value) {
	  this.graphSection = value;
   }

   /**
	* Gets the value of the graphSectionOffset property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public JAXBElement<Float> getGraphSectionOffset() {
	  return graphSectionOffset;
   }

   /**
	* Sets the value of the graphSectionOffset property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public void setGraphSectionOffset(JAXBElement<Float> value) {
	  this.graphSectionOffset = value;
   }


   /**
	* список перевозчиков
	* <p>
	* <p>
	* <p>Java class for anonymous complex type.
	* <p>
	* <p>The following schema fragment specifies the expected content contained within this class.
	* <p>
	* <pre>
	* &lt;complexType>
	*   &lt;complexContent>
	*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	*       &lt;sequence>
	*         &lt;element name="agency" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RAgency" maxOccurs="unbounded"/>
	*       &lt;/sequence>
	*     &lt;/restriction>
	*   &lt;/complexContent>
	* &lt;/complexType>
	* </pre>
	*/
   @XmlAccessorType(XmlAccessType.FIELD)
   @XmlType(name = "", propOrder = {
	   "agencies"
   })
   public static class Agencies {

	  @XmlElement(name = "agency", required = true, nillable = true)
	  protected List<RAgency> agencies;

	  /**
	   * Gets the value of the agencies property.
	   * <p>
	   * <p>
	   * This accessor method returns a reference to the live list,
	   * not a snapshot. Therefore any modification you make to the
	   * returned list will be present inside the JAXB object.
	   * This is why there is not a <CODE>set</CODE> method for the agencies property.
	   * <p>
	   * <p>
	   * For example, to add a new item, do as follows:
	   * <pre>
	   *    getAgencies().add(newItem);
	   * </pre>
	   * <p>
	   * <p>
	   * <p>
	   * Objects of the following type(s) are allowed in the list
	   * {@link RAgency }
	   */
	  public List<RAgency> getAgencies() {
		 if (agencies == null) {
			agencies = new ArrayList<RAgency>();
		 }
		 return this.agencies;
	  }

   }


   /**
	* список маршрутов
	* <p>
	* <p>
	* <p>Java class for anonymous complex type.
	* <p>
	* <p>The following schema fragment specifies the expected content contained within this class.
	* <p>
	* <pre>
	* &lt;complexType>
	*   &lt;complexContent>
	*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	*       &lt;sequence>
	*         &lt;element name="route" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRoute" maxOccurs="unbounded"/>
	*       &lt;/sequence>
	*     &lt;/restriction>
	*   &lt;/complexContent>
	* &lt;/complexType>
	* </pre>
	*/
   @XmlAccessorType(XmlAccessType.FIELD)
   @XmlType(name = "", propOrder = {
	   "routes"
   })
   public static class Routes {

	  @XmlElement(name = "route", required = true, nillable = true)
	  protected List<RRoute> routes;

	  /**
	   * Gets the value of the routes property.
	   * <p>
	   * <p>
	   * This accessor method returns a reference to the live list,
	   * not a snapshot. Therefore any modification you make to the
	   * returned list will be present inside the JAXB object.
	   * This is why there is not a <CODE>set</CODE> method for the routes property.
	   * <p>
	   * <p>
	   * For example, to add a new item, do as follows:
	   * <pre>
	   *    getRoutes().add(newItem);
	   * </pre>
	   * <p>
	   * <p>
	   * <p>
	   * Objects of the following type(s) are allowed in the list
	   * {@link RRoute }
	   */
	  public List<RRoute> getRoutes() {
		 if (routes == null) {
			routes = new ArrayList<RRoute>();
		 }
		 return this.routes;
	  }

   }


   /**
	* список типов подвижного состава
	* <p>
	* <p>
	* <p>Java class for anonymous complex type.
	* <p>
	* <p>The following schema fragment specifies the expected content contained within this class.
	* <p>
	* <pre>
	* &lt;complexType>
	*   &lt;complexContent>
	*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	*       &lt;sequence>
	*         &lt;element name="vehicleType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RVehicleType" maxOccurs="unbounded"/>
	*       &lt;/sequence>
	*     &lt;/restriction>
	*   &lt;/complexContent>
	* &lt;/complexType>
	* </pre>
	*/
   @XmlAccessorType(XmlAccessType.FIELD)
   @XmlType(name = "", propOrder = {
	   "vehicleTypes"
   })
   public static class VehicleTypes {

	  @XmlElement(name = "vehicleType", required = true, nillable = true)
	  protected List<RVehicleType> vehicleTypes;

	  /**
	   * Gets the value of the vehicleTypes property.
	   * <p>
	   * <p>
	   * This accessor method returns a reference to the live list,
	   * not a snapshot. Therefore any modification you make to the
	   * returned list will be present inside the JAXB object.
	   * This is why there is not a <CODE>set</CODE> method for the vehicleTypes property.
	   * <p>
	   * <p>
	   * For example, to add a new item, do as follows:
	   * <pre>
	   *    getVehicleTypes().add(newItem);
	   * </pre>
	   * <p>
	   * <p>
	   * <p>
	   * Objects of the following type(s) are allowed in the list
	   * {@link RVehicleType }
	   */
	  public List<RVehicleType> getVehicleTypes() {
		 if (vehicleTypes == null) {
			vehicleTypes = new ArrayList<RVehicleType>();
		 }
		 return this.vehicleTypes;
	  }

   }

}
