//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * ОМК - Муниципальные районы (OMKTE_P1.DBF)
 * <p>
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;tags xmlns="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:gismgt="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:p578540_="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:p729618_="http://java.sun.com/xml/ns/jaxb" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;&lt;tag&gt;mtrans&lt;/tag&gt;&lt;/tags&gt;
 * </pre>
 * <p>
 * <p>
 * <p>Java class for TRegion complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TRegion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://mappl.ru/2015/XMLSchema/GISMGT}TDictionaryObject"/>
 *         &lt;element name="omkCode" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TOmkCode" minOccurs="0"/>
 *         &lt;element name="name" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TName" minOccurs="0"/>
 *         &lt;element name="shortName" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TName" minOccurs="0"/>
 *         &lt;element name="translitName" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TName" minOccurs="0"/>
 *         &lt;element name="territorialUnitTypeCode" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TName" minOccurs="0"/>
 *         &lt;element name="okatoCode" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TName" minOccurs="0"/>
 *         &lt;element name="districtCode" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TName" minOccurs="0"/>
 *         &lt;element name="district" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RDistrict" minOccurs="0"/>
 *         &lt;element name="egkoRegions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="region" type="{http://mappl.ru/2015/XMLSchema/GISMGT}REGKORegion" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRegion", propOrder = {
	"muid",
	"version",
	"signDeleted",
	"omkCode",
	"name",
	"shortName",
	"translitName",
	"territorialUnitTypeCode",
	"okatoCode",
	"districtCode",
	"district",
	"egkoRegions"
})
public class TRegion {

   @XmlElement(required = true)
   protected String muid;
   @XmlElement(defaultValue = "1")
   protected BigInteger version;
   @XmlElementRef(name = "signDeleted", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> signDeleted;
   @XmlElementRef(name = "omkCode", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> omkCode;
   @XmlElementRef(name = "name", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> name;
   @XmlElementRef(name = "shortName", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> shortName;
   @XmlElementRef(name = "translitName", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> translitName;
   @XmlElementRef(name = "territorialUnitTypeCode", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> territorialUnitTypeCode;
   @XmlElementRef(name = "okatoCode", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> okatoCode;
   @XmlElementRef(name = "districtCode", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> districtCode;
   @XmlElementRef(name = "district", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RDistrict> district;
   protected TRegion.EgkoRegions egkoRegions;

   /**
	* Gets the value of the muid property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getMuid() {
	  return muid;
   }

   /**
	* Sets the value of the muid property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setMuid(String value) {
	  this.muid = value;
   }

   /**
	* Gets the value of the version property.
	*
	* @return possible object is
	* {@link BigInteger }
	*/
   public BigInteger getVersion() {
	  return version;
   }

   /**
	* Sets the value of the version property.
	*
	* @param value allowed object is
	*              {@link BigInteger }
	*/
   public void setVersion(BigInteger value) {
	  this.version = value;
   }

   /**
	* Gets the value of the signDeleted property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getSignDeleted() {
	  return signDeleted;
   }

   /**
	* Sets the value of the signDeleted property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setSignDeleted(JAXBElement<BigInteger> value) {
	  this.signDeleted = value;
   }

   /**
	* Gets the value of the omkCode property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getOmkCode() {
	  return omkCode;
   }

   /**
	* Sets the value of the omkCode property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setOmkCode(JAXBElement<BigInteger> value) {
	  this.omkCode = value;
   }

   /**
	* Gets the value of the name property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getName() {
	  return name;
   }

   /**
	* Sets the value of the name property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setName(JAXBElement<String> value) {
	  this.name = value;
   }

   /**
	* Gets the value of the shortName property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getShortName() {
	  return shortName;
   }

   /**
	* Sets the value of the shortName property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setShortName(JAXBElement<String> value) {
	  this.shortName = value;
   }

   /**
	* Gets the value of the translitName property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getTranslitName() {
	  return translitName;
   }

   /**
	* Sets the value of the translitName property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setTranslitName(JAXBElement<String> value) {
	  this.translitName = value;
   }

   /**
	* Gets the value of the territorialUnitTypeCode property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getTerritorialUnitTypeCode() {
	  return territorialUnitTypeCode;
   }

   /**
	* Sets the value of the territorialUnitTypeCode property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setTerritorialUnitTypeCode(JAXBElement<String> value) {
	  this.territorialUnitTypeCode = value;
   }

   /**
	* Gets the value of the okatoCode property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getOkatoCode() {
	  return okatoCode;
   }

   /**
	* Sets the value of the okatoCode property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setOkatoCode(JAXBElement<String> value) {
	  this.okatoCode = value;
   }

   /**
	* Gets the value of the districtCode property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getDistrictCode() {
	  return districtCode;
   }

   /**
	* Sets the value of the districtCode property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setDistrictCode(JAXBElement<String> value) {
	  this.districtCode = value;
   }

   /**
	* Gets the value of the district property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RDistrict }{@code >}
	*/
   public JAXBElement<RDistrict> getDistrict() {
	  return district;
   }

   /**
	* Sets the value of the district property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RDistrict }{@code >}
	*/
   public void setDistrict(JAXBElement<RDistrict> value) {
	  this.district = value;
   }

   /**
	* Gets the value of the egkoRegions property.
	*
	* @return possible object is
	* {@link TRegion.EgkoRegions }
	*/
   public TRegion.EgkoRegions getEgkoRegions() {
	  return egkoRegions;
   }

   /**
	* Sets the value of the egkoRegions property.
	*
	* @param value allowed object is
	*              {@link TRegion.EgkoRegions }
	*/
   public void setEgkoRegions(TRegion.EgkoRegions value) {
	  this.egkoRegions = value;
   }


   /**
	* <p>Java class for anonymous complex type.
	* <p>
	* <p>The following schema fragment specifies the expected content contained within this class.
	* <p>
	* <pre>
	* &lt;complexType>
	*   &lt;complexContent>
	*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	*       &lt;sequence>
	*         &lt;element name="region" type="{http://mappl.ru/2015/XMLSchema/GISMGT}REGKORegion" maxOccurs="unbounded"/>
	*       &lt;/sequence>
	*     &lt;/restriction>
	*   &lt;/complexContent>
	* &lt;/complexType>
	* </pre>
	*/
   @XmlAccessorType(XmlAccessType.FIELD)
   @XmlType(name = "", propOrder = {
	   "regions"
   })
   public static class EgkoRegions {

	  @XmlElement(name = "region", required = true, nillable = true)
	  protected List<REGKORegion> regions;

	  /**
	   * Gets the value of the regions property.
	   * <p>
	   * <p>
	   * This accessor method returns a reference to the live list,
	   * not a snapshot. Therefore any modification you make to the
	   * returned list will be present inside the JAXB object.
	   * This is why there is not a <CODE>set</CODE> method for the regions property.
	   * <p>
	   * <p>
	   * For example, to add a new item, do as follows:
	   * <pre>
	   *    getRegions().add(newItem);
	   * </pre>
	   * <p>
	   * <p>
	   * <p>
	   * Objects of the following type(s) are allowed in the list
	   * {@link REGKORegion }
	   */
	  public List<REGKORegion> getRegions() {
		 if (regions == null) {
			regions = new ArrayList<REGKORegion>();
		 }
		 return this.regions;
	  }

   }

}
