//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * Нулевые рейсы
 * <p>
 * <p>
 * <p>Java class for TRouteNullRound complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TRouteNullRound">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://mappl.ru/2015/XMLSchema/GISMGT}TDictionaryObject"/>
 *         &lt;element name="routeVariant" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRouteVariant" minOccurs="0"/>
 *         &lt;element name="code" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TCode" minOccurs="0"/>
 *         &lt;element name="type" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRouteNullRoundType" minOccurs="0"/>
 *         &lt;element name="park1" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RPark" minOccurs="0"/>
 *         &lt;element name="stopPlace1" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStopPlace" minOccurs="0"/>
 *         &lt;element name="park2" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RPark" minOccurs="0"/>
 *         &lt;element name="stopPlace2" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStopPlace" minOccurs="0"/>
 *         &lt;element name="park3" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RPark" minOccurs="0"/>
 *         &lt;element name="stopPlace3" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStopPlace" minOccurs="0"/>
 *         &lt;element name="comment" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComment" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRouteNullRound", propOrder = {
	"muid",
	"version",
	"signDeleted",
	"routeVariant",
	"code",
	"type",
	"park1",
	"stopPlace1",
	"park2",
	"stopPlace2",
	"park3",
	"stopPlace3",
	"comment"
})
public class TRouteNullRound {

   @XmlElement(required = true)
   protected String muid;
   @XmlElement(defaultValue = "1")
   protected BigInteger version;
   @XmlElementRef(name = "signDeleted", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> signDeleted;
   @XmlElementRef(name = "routeVariant", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RRouteVariant> routeVariant;
   @XmlElementRef(name = "code", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> code;
   @XmlElementRef(name = "type", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RRouteNullRoundType> type;
   @XmlElementRef(name = "park1", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RPark> park1;
   @XmlElementRef(name = "stopPlace1", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RStopPlace> stopPlace1;
   @XmlElementRef(name = "park2", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RPark> park2;
   @XmlElementRef(name = "stopPlace2", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RStopPlace> stopPlace2;
   @XmlElementRef(name = "park3", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RPark> park3;
   @XmlElementRef(name = "stopPlace3", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RStopPlace> stopPlace3;
   @XmlElementRef(name = "comment", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> comment;

   /**
	* Gets the value of the muid property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getMuid() {
	  return muid;
   }

   /**
	* Sets the value of the muid property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setMuid(String value) {
	  this.muid = value;
   }

   /**
	* Gets the value of the version property.
	*
	* @return possible object is
	* {@link BigInteger }
	*/
   public BigInteger getVersion() {
	  return version;
   }

   /**
	* Sets the value of the version property.
	*
	* @param value allowed object is
	*              {@link BigInteger }
	*/
   public void setVersion(BigInteger value) {
	  this.version = value;
   }

   /**
	* Gets the value of the signDeleted property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getSignDeleted() {
	  return signDeleted;
   }

   /**
	* Sets the value of the signDeleted property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setSignDeleted(JAXBElement<BigInteger> value) {
	  this.signDeleted = value;
   }

   /**
	* Gets the value of the routeVariant property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RRouteVariant }{@code >}
	*/
   public JAXBElement<RRouteVariant> getRouteVariant() {
	  return routeVariant;
   }

   /**
	* Sets the value of the routeVariant property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RRouteVariant }{@code >}
	*/
   public void setRouteVariant(JAXBElement<RRouteVariant> value) {
	  this.routeVariant = value;
   }

   /**
	* Gets the value of the code property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getCode() {
	  return code;
   }

   /**
	* Sets the value of the code property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setCode(JAXBElement<String> value) {
	  this.code = value;
   }

   /**
	* Gets the value of the type property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RRouteNullRoundType }{@code >}
	*/
   public JAXBElement<RRouteNullRoundType> getType() {
	  return type;
   }

   /**
	* Sets the value of the type property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RRouteNullRoundType }{@code >}
	*/
   public void setType(JAXBElement<RRouteNullRoundType> value) {
	  this.type = value;
   }

   /**
	* Gets the value of the park1 property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RPark }{@code >}
	*/
   public JAXBElement<RPark> getPark1() {
	  return park1;
   }

   /**
	* Sets the value of the park1 property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RPark }{@code >}
	*/
   public void setPark1(JAXBElement<RPark> value) {
	  this.park1 = value;
   }

   /**
	* Gets the value of the stopPlace1 property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RStopPlace }{@code >}
	*/
   public JAXBElement<RStopPlace> getStopPlace1() {
	  return stopPlace1;
   }

   /**
	* Sets the value of the stopPlace1 property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RStopPlace }{@code >}
	*/
   public void setStopPlace1(JAXBElement<RStopPlace> value) {
	  this.stopPlace1 = value;
   }

   /**
	* Gets the value of the park2 property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RPark }{@code >}
	*/
   public JAXBElement<RPark> getPark2() {
	  return park2;
   }

   /**
	* Sets the value of the park2 property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RPark }{@code >}
	*/
   public void setPark2(JAXBElement<RPark> value) {
	  this.park2 = value;
   }

   /**
	* Gets the value of the stopPlace2 property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RStopPlace }{@code >}
	*/
   public JAXBElement<RStopPlace> getStopPlace2() {
	  return stopPlace2;
   }

   /**
	* Sets the value of the stopPlace2 property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RStopPlace }{@code >}
	*/
   public void setStopPlace2(JAXBElement<RStopPlace> value) {
	  this.stopPlace2 = value;
   }

   /**
	* Gets the value of the park3 property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RPark }{@code >}
	*/
   public JAXBElement<RPark> getPark3() {
	  return park3;
   }

   /**
	* Sets the value of the park3 property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RPark }{@code >}
	*/
   public void setPark3(JAXBElement<RPark> value) {
	  this.park3 = value;
   }

   /**
	* Gets the value of the stopPlace3 property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RStopPlace }{@code >}
	*/
   public JAXBElement<RStopPlace> getStopPlace3() {
	  return stopPlace3;
   }

   /**
	* Sets the value of the stopPlace3 property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RStopPlace }{@code >}
	*/
   public void setStopPlace3(JAXBElement<RStopPlace> value) {
	  this.stopPlace3 = value;
   }

   /**
	* Gets the value of the comment property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getComment() {
	  return comment;
   }

   /**
	* Sets the value of the comment property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setComment(JAXBElement<String> value) {
	  this.comment = value;
   }

}
