//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * Производственные рейсы
 * <p>
 * <p>
 * <p>Java class for TRouteRound complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TRouteRound">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://mappl.ru/2015/XMLSchema/GISMGT}TDictionaryObject"/>
 *         &lt;element name="routeVariant" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRouteVariant" minOccurs="0"/>
 *         &lt;element name="code" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TCode" minOccurs="0"/>
 *         &lt;element name="type" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRouteRoundType" minOccurs="0"/>
 *         &lt;element name="stopPlaceA" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStopPlace" minOccurs="0"/>
 *         &lt;element name="stopPlaceB" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStopPlace" minOccurs="0"/>
 *         &lt;element name="terminalStationA" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RTerminalStation" minOccurs="0"/>
 *         &lt;element name="terminalStationB" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RTerminalStation" minOccurs="0"/>
 *         &lt;element name="terminalStationC" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RTerminalStation" minOccurs="0"/>
 *         &lt;element name="terminalPointZoneA" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RTerminalPointZone" minOccurs="0"/>
 *         &lt;element name="terminalPointZoneB" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RTerminalPointZone" minOccurs="0"/>
 *         &lt;element name="averageLength" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TLength" minOccurs="0"/>
 *         &lt;element name="averageLengthFixed" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TLength" minOccurs="0"/>
 *         &lt;element name="specification1" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSpecification" minOccurs="0"/>
 *         &lt;element name="specification2" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSpecification" minOccurs="0"/>
 *         &lt;element name="comment" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComment" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRouteRound", propOrder = {
	"muid",
	"version",
	"signDeleted",
	"routeVariant",
	"code",
	"type",
	"stopPlaceA",
	"stopPlaceB",
	"terminalStationA",
	"terminalStationB",
	"terminalStationC",
	"terminalPointZoneA",
	"terminalPointZoneB",
	"averageLength",
	"averageLengthFixed",
	"specification1",
	"specification2",
	"comment"
})
public class TRouteRound {

   @XmlElement(required = true)
   protected String muid;
   @XmlElement(defaultValue = "1")
   protected BigInteger version;
   @XmlElementRef(name = "signDeleted", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> signDeleted;
   @XmlElementRef(name = "routeVariant", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RRouteVariant> routeVariant;
   @XmlElementRef(name = "code", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> code;
   @XmlElementRef(name = "type", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RRouteRoundType> type;
   @XmlElementRef(name = "stopPlaceA", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RStopPlace> stopPlaceA;
   @XmlElementRef(name = "stopPlaceB", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RStopPlace> stopPlaceB;
   @XmlElementRef(name = "terminalStationA", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RTerminalStation> terminalStationA;
   @XmlElementRef(name = "terminalStationB", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RTerminalStation> terminalStationB;
   @XmlElementRef(name = "terminalStationC", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RTerminalStation> terminalStationC;
   @XmlElementRef(name = "terminalPointZoneA", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RTerminalPointZone> terminalPointZoneA;
   @XmlElementRef(name = "terminalPointZoneB", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RTerminalPointZone> terminalPointZoneB;
   @XmlElementRef(name = "averageLength", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Float> averageLength;
   @XmlElementRef(name = "averageLengthFixed", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Float> averageLengthFixed;
   @XmlElementRef(name = "specification1", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> specification1;
   @XmlElementRef(name = "specification2", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> specification2;
   @XmlElementRef(name = "comment", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> comment;

   /**
	* Gets the value of the muid property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getMuid() {
	  return muid;
   }

   /**
	* Sets the value of the muid property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setMuid(String value) {
	  this.muid = value;
   }

   /**
	* Gets the value of the version property.
	*
	* @return possible object is
	* {@link BigInteger }
	*/
   public BigInteger getVersion() {
	  return version;
   }

   /**
	* Sets the value of the version property.
	*
	* @param value allowed object is
	*              {@link BigInteger }
	*/
   public void setVersion(BigInteger value) {
	  this.version = value;
   }

   /**
	* Gets the value of the signDeleted property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getSignDeleted() {
	  return signDeleted;
   }

   /**
	* Sets the value of the signDeleted property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setSignDeleted(JAXBElement<BigInteger> value) {
	  this.signDeleted = value;
   }

   /**
	* Gets the value of the routeVariant property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RRouteVariant }{@code >}
	*/
   public JAXBElement<RRouteVariant> getRouteVariant() {
	  return routeVariant;
   }

   /**
	* Sets the value of the routeVariant property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RRouteVariant }{@code >}
	*/
   public void setRouteVariant(JAXBElement<RRouteVariant> value) {
	  this.routeVariant = value;
   }

   /**
	* Gets the value of the code property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getCode() {
	  return code;
   }

   /**
	* Sets the value of the code property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setCode(JAXBElement<String> value) {
	  this.code = value;
   }

   /**
	* Gets the value of the type property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RRouteRoundType }{@code >}
	*/
   public JAXBElement<RRouteRoundType> getType() {
	  return type;
   }

   /**
	* Sets the value of the type property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RRouteRoundType }{@code >}
	*/
   public void setType(JAXBElement<RRouteRoundType> value) {
	  this.type = value;
   }

   /**
	* Gets the value of the stopPlaceA property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RStopPlace }{@code >}
	*/
   public JAXBElement<RStopPlace> getStopPlaceA() {
	  return stopPlaceA;
   }

   /**
	* Sets the value of the stopPlaceA property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RStopPlace }{@code >}
	*/
   public void setStopPlaceA(JAXBElement<RStopPlace> value) {
	  this.stopPlaceA = value;
   }

   /**
	* Gets the value of the stopPlaceB property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RStopPlace }{@code >}
	*/
   public JAXBElement<RStopPlace> getStopPlaceB() {
	  return stopPlaceB;
   }

   /**
	* Sets the value of the stopPlaceB property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RStopPlace }{@code >}
	*/
   public void setStopPlaceB(JAXBElement<RStopPlace> value) {
	  this.stopPlaceB = value;
   }

   /**
	* Gets the value of the terminalStationA property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RTerminalStation }{@code >}
	*/
   public JAXBElement<RTerminalStation> getTerminalStationA() {
	  return terminalStationA;
   }

   /**
	* Sets the value of the terminalStationA property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RTerminalStation }{@code >}
	*/
   public void setTerminalStationA(JAXBElement<RTerminalStation> value) {
	  this.terminalStationA = value;
   }

   /**
	* Gets the value of the terminalStationB property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RTerminalStation }{@code >}
	*/
   public JAXBElement<RTerminalStation> getTerminalStationB() {
	  return terminalStationB;
   }

   /**
	* Sets the value of the terminalStationB property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RTerminalStation }{@code >}
	*/
   public void setTerminalStationB(JAXBElement<RTerminalStation> value) {
	  this.terminalStationB = value;
   }

   /**
	* Gets the value of the terminalStationC property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RTerminalStation }{@code >}
	*/
   public JAXBElement<RTerminalStation> getTerminalStationC() {
	  return terminalStationC;
   }

   /**
	* Sets the value of the terminalStationC property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RTerminalStation }{@code >}
	*/
   public void setTerminalStationC(JAXBElement<RTerminalStation> value) {
	  this.terminalStationC = value;
   }

   /**
	* Gets the value of the terminalPointZoneA property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RTerminalPointZone }{@code >}
	*/
   public JAXBElement<RTerminalPointZone> getTerminalPointZoneA() {
	  return terminalPointZoneA;
   }

   /**
	* Sets the value of the terminalPointZoneA property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RTerminalPointZone }{@code >}
	*/
   public void setTerminalPointZoneA(JAXBElement<RTerminalPointZone> value) {
	  this.terminalPointZoneA = value;
   }

   /**
	* Gets the value of the terminalPointZoneB property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RTerminalPointZone }{@code >}
	*/
   public JAXBElement<RTerminalPointZone> getTerminalPointZoneB() {
	  return terminalPointZoneB;
   }

   /**
	* Sets the value of the terminalPointZoneB property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RTerminalPointZone }{@code >}
	*/
   public void setTerminalPointZoneB(JAXBElement<RTerminalPointZone> value) {
	  this.terminalPointZoneB = value;
   }

   /**
	* Gets the value of the averageLength property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public JAXBElement<Float> getAverageLength() {
	  return averageLength;
   }

   /**
	* Sets the value of the averageLength property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public void setAverageLength(JAXBElement<Float> value) {
	  this.averageLength = value;
   }

   /**
	* Gets the value of the averageLengthFixed property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public JAXBElement<Float> getAverageLengthFixed() {
	  return averageLengthFixed;
   }

   /**
	* Sets the value of the averageLengthFixed property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public void setAverageLengthFixed(JAXBElement<Float> value) {
	  this.averageLengthFixed = value;
   }

   /**
	* Gets the value of the specification1 property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getSpecification1() {
	  return specification1;
   }

   /**
	* Sets the value of the specification1 property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setSpecification1(JAXBElement<String> value) {
	  this.specification1 = value;
   }

   /**
	* Gets the value of the specification2 property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getSpecification2() {
	  return specification2;
   }

   /**
	* Sets the value of the specification2 property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setSpecification2(JAXBElement<String> value) {
	  this.specification2 = value;
   }

   /**
	* Gets the value of the comment property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getComment() {
	  return comment;
   }

   /**
	* Sets the value of the comment property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setComment(JAXBElement<String> value) {
	  this.comment = value;
   }

}
