//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * Таблица связей Траектории маршрутов - Дуги графа
 * <p>
 * <p>
 * <p>Java class for TRouteTrajectories2GraphSections complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TRouteTrajectories2GraphSections">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://mappl.ru/2015/XMLSchema/GISMGT}TDictionaryObject"/>
 *         &lt;element name="routeTrajectory" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRouteTrajectory" maxOccurs="unbounded"/>
 *         &lt;element name="graphSection" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RGraphSection" maxOccurs="unbounded"/>
 *         &lt;element name="index" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TIndex" minOccurs="0"/>
 *         &lt;element name="graphSectionStartOffset" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TLength" minOccurs="0"/>
 *         &lt;element name="graphSectionEndOffset" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TLength" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRouteTrajectories2GraphSections", propOrder = {
	"muid",
	"version",
	"signDeleted",
	"routeTrajectories",
	"graphSections",
	"index",
	"graphSectionStartOffset",
	"graphSectionEndOffset"
})
public class TRouteTrajectories2GraphSections {

   @XmlElement(required = true)
   protected String muid;
   @XmlElement(defaultValue = "1")
   protected BigInteger version;
   @XmlElementRef(name = "signDeleted", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> signDeleted;
   @XmlElement(name = "routeTrajectory", required = true, nillable = true)
   protected List<RRouteTrajectory> routeTrajectories;
   @XmlElement(name = "graphSection", required = true, nillable = true)
   protected List<RGraphSection> graphSections;
   @XmlElementRef(name = "index", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> index;
   @XmlElementRef(name = "graphSectionStartOffset", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Float> graphSectionStartOffset;
   @XmlElementRef(name = "graphSectionEndOffset", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Float> graphSectionEndOffset;

   /**
	* Gets the value of the muid property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getMuid() {
	  return muid;
   }

   /**
	* Sets the value of the muid property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setMuid(String value) {
	  this.muid = value;
   }

   /**
	* Gets the value of the version property.
	*
	* @return possible object is
	* {@link BigInteger }
	*/
   public BigInteger getVersion() {
	  return version;
   }

   /**
	* Sets the value of the version property.
	*
	* @param value allowed object is
	*              {@link BigInteger }
	*/
   public void setVersion(BigInteger value) {
	  this.version = value;
   }

   /**
	* Gets the value of the signDeleted property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getSignDeleted() {
	  return signDeleted;
   }

   /**
	* Sets the value of the signDeleted property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setSignDeleted(JAXBElement<BigInteger> value) {
	  this.signDeleted = value;
   }

   /**
	* Gets the value of the routeTrajectories property.
	* <p>
	* <p>
	* This accessor method returns a reference to the live list,
	* not a snapshot. Therefore any modification you make to the
	* returned list will be present inside the JAXB object.
	* This is why there is not a <CODE>set</CODE> method for the routeTrajectories property.
	* <p>
	* <p>
	* For example, to add a new item, do as follows:
	* <pre>
	*    getRouteTrajectories().add(newItem);
	* </pre>
	* <p>
	* <p>
	* <p>
	* Objects of the following type(s) are allowed in the list
	* {@link RRouteTrajectory }
	*/
   public List<RRouteTrajectory> getRouteTrajectories() {
	  if (routeTrajectories == null) {
		 routeTrajectories = new ArrayList<RRouteTrajectory>();
	  }
	  return this.routeTrajectories;
   }

   /**
	* Gets the value of the graphSections property.
	* <p>
	* <p>
	* This accessor method returns a reference to the live list,
	* not a snapshot. Therefore any modification you make to the
	* returned list will be present inside the JAXB object.
	* This is why there is not a <CODE>set</CODE> method for the graphSections property.
	* <p>
	* <p>
	* For example, to add a new item, do as follows:
	* <pre>
	*    getGraphSections().add(newItem);
	* </pre>
	* <p>
	* <p>
	* <p>
	* Objects of the following type(s) are allowed in the list
	* {@link RGraphSection }
	*/
   public List<RGraphSection> getGraphSections() {
	  if (graphSections == null) {
		 graphSections = new ArrayList<RGraphSection>();
	  }
	  return this.graphSections;
   }

   /**
	* Gets the value of the index property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getIndex() {
	  return index;
   }

   /**
	* Sets the value of the index property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setIndex(JAXBElement<BigInteger> value) {
	  this.index = value;
   }

   /**
	* Gets the value of the graphSectionStartOffset property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public JAXBElement<Float> getGraphSectionStartOffset() {
	  return graphSectionStartOffset;
   }

   /**
	* Sets the value of the graphSectionStartOffset property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public void setGraphSectionStartOffset(JAXBElement<Float> value) {
	  this.graphSectionStartOffset = value;
   }

   /**
	* Gets the value of the graphSectionEndOffset property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public JAXBElement<Float> getGraphSectionEndOffset() {
	  return graphSectionEndOffset;
   }

   /**
	* Sets the value of the graphSectionEndOffset property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public void setGraphSectionEndOffset(JAXBElement<Float> value) {
	  this.graphSectionEndOffset = value;
   }

}
