//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * Таблица связей Траектории маршуртов-Места остановки
 * <p>
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;tags xmlns="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:gismgt="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:p578540_="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:p729618_="http://java.sun.com/xml/ns/jaxb" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;&lt;tag&gt;mtrans&lt;/tag&gt;&lt;/tags&gt;
 * </pre>
 * <p>
 * <p>
 * <p>Java class for TRouteTrajectories2StopPlaces complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TRouteTrajectories2StopPlaces">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://mappl.ru/2015/XMLSchema/GISMGT}TDictionaryObject"/>
 *         &lt;element name="routeTrajectory" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRouteTrajectory" minOccurs="0"/>
 *         &lt;element name="stopPlace" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStopPlace" minOccurs="0"/>
 *         &lt;element name="mode" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStopMode" minOccurs="0"/>
 *         &lt;element name="type" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStopType" minOccurs="0"/>
 *         &lt;element name="index" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TIndex" minOccurs="0"/>
 *         &lt;element name="index2" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TIndex" minOccurs="0"/>
 *         &lt;element name="lengthSector" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TLength" minOccurs="0"/>
 *         &lt;element name="comment" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComment" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRouteTrajectories2StopPlaces", propOrder = {
	"muid",
	"version",
	"signDeleted",
	"routeTrajectory",
	"stopPlace",
	"mode",
	"type",
	"index",
	"index2",
	"lengthSector",
	"comment"
})
public class TRouteTrajectories2StopPlaces {

   @XmlElement(required = true)
   protected String muid;
   @XmlElement(defaultValue = "1")
   protected BigInteger version;
   @XmlElementRef(name = "signDeleted", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> signDeleted;
   @XmlElementRef(name = "routeTrajectory", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RRouteTrajectory> routeTrajectory;
   @XmlElementRef(name = "stopPlace", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RStopPlace> stopPlace;
   @XmlElementRef(name = "mode", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RStopMode> mode;
   @XmlElementRef(name = "type", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RStopType> type;
   @XmlElementRef(name = "index", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> index;
   protected BigInteger index2;
   @XmlElementRef(name = "lengthSector", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Float> lengthSector;
   @XmlElementRef(name = "comment", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> comment;

   /**
	* Gets the value of the muid property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getMuid() {
	  return muid;
   }

   /**
	* Sets the value of the muid property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setMuid(String value) {
	  this.muid = value;
   }

   /**
	* Gets the value of the version property.
	*
	* @return possible object is
	* {@link BigInteger }
	*/
   public BigInteger getVersion() {
	  return version;
   }

   /**
	* Sets the value of the version property.
	*
	* @param value allowed object is
	*              {@link BigInteger }
	*/
   public void setVersion(BigInteger value) {
	  this.version = value;
   }

   /**
	* Gets the value of the signDeleted property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getSignDeleted() {
	  return signDeleted;
   }

   /**
	* Sets the value of the signDeleted property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setSignDeleted(JAXBElement<BigInteger> value) {
	  this.signDeleted = value;
   }

   /**
	* Gets the value of the routeTrajectory property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RRouteTrajectory }{@code >}
	*/
   public JAXBElement<RRouteTrajectory> getRouteTrajectory() {
	  return routeTrajectory;
   }

   /**
	* Sets the value of the routeTrajectory property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RRouteTrajectory }{@code >}
	*/
   public void setRouteTrajectory(JAXBElement<RRouteTrajectory> value) {
	  this.routeTrajectory = value;
   }

   /**
	* Gets the value of the stopPlace property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RStopPlace }{@code >}
	*/
   public JAXBElement<RStopPlace> getStopPlace() {
	  return stopPlace;
   }

   /**
	* Sets the value of the stopPlace property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RStopPlace }{@code >}
	*/
   public void setStopPlace(JAXBElement<RStopPlace> value) {
	  this.stopPlace = value;
   }

   /**
	* Gets the value of the mode property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RStopMode }{@code >}
	*/
   public JAXBElement<RStopMode> getMode() {
	  return mode;
   }

   /**
	* Sets the value of the mode property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RStopMode }{@code >}
	*/
   public void setMode(JAXBElement<RStopMode> value) {
	  this.mode = value;
   }

   /**
	* Gets the value of the type property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RStopType }{@code >}
	*/
   public JAXBElement<RStopType> getType() {
	  return type;
   }

   /**
	* Sets the value of the type property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RStopType }{@code >}
	*/
   public void setType(JAXBElement<RStopType> value) {
	  this.type = value;
   }

   /**
	* Gets the value of the index property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getIndex() {
	  return index;
   }

   /**
	* Sets the value of the index property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setIndex(JAXBElement<BigInteger> value) {
	  this.index = value;
   }

   /**
	* Gets the value of the index2 property.
	*
	* @return possible object is
	* {@link BigInteger }
	*/
   public BigInteger getIndex2() {
	  return index2;
   }

   /**
	* Sets the value of the index2 property.
	*
	* @param value allowed object is
	*              {@link BigInteger }
	*/
   public void setIndex2(BigInteger value) {
	  this.index2 = value;
   }

   /**
	* Gets the value of the lengthSector property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public JAXBElement<Float> getLengthSector() {
	  return lengthSector;
   }

   /**
	* Sets the value of the lengthSector property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public void setLengthSector(JAXBElement<Float> value) {
	  this.lengthSector = value;
   }

   /**
	* Gets the value of the comment property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getComment() {
	  return comment;
   }

   /**
	* Sets the value of the comment property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setComment(JAXBElement<String> value) {
	  this.comment = value;
   }

}
