//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * Варианты маршрутов
 * <p>
 * <p>
 * <p>Java class for TRouteVariant complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TRouteVariant">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://mappl.ru/2015/XMLSchema/GISMGT}TDictionaryObject"/>
 *         &lt;element name="route" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRoute" minOccurs="0"/>
 *         &lt;element name="startDate" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TDate" minOccurs="0"/>
 *         &lt;element name="endDate" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TDate" minOccurs="0"/>
 *         &lt;element name="type" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRouteVariantType" minOccurs="0"/>
 *         &lt;element name="order" type="{http://mappl.ru/2015/XMLSchema/GISMGT}ROrder" minOccurs="0"/>
 *         &lt;element name="comment" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComment" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRouteVariant", propOrder = {
	"muid",
	"version",
	"signDeleted",
	"route",
	"startDate",
	"endDate",
	"type",
	"order",
	"comment"
})
public class TRouteVariant {

   @XmlElement(required = true)
   protected String muid;
   @XmlElement(defaultValue = "1")
   protected BigInteger version;
   @XmlElementRef(name = "signDeleted", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> signDeleted;
   @XmlElementRef(name = "route", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RRoute> route;
   @XmlElementRef(name = "startDate", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<XMLGregorianCalendar> startDate;
   @XmlElementRef(name = "endDate", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<XMLGregorianCalendar> endDate;
   @XmlElementRef(name = "type", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RRouteVariantType> type;
   @XmlElementRef(name = "order", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<ROrder> order;
   @XmlElementRef(name = "comment", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> comment;

   /**
	* Gets the value of the muid property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getMuid() {
	  return muid;
   }

   /**
	* Sets the value of the muid property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setMuid(String value) {
	  this.muid = value;
   }

   /**
	* Gets the value of the version property.
	*
	* @return possible object is
	* {@link BigInteger }
	*/
   public BigInteger getVersion() {
	  return version;
   }

   /**
	* Sets the value of the version property.
	*
	* @param value allowed object is
	*              {@link BigInteger }
	*/
   public void setVersion(BigInteger value) {
	  this.version = value;
   }

   /**
	* Gets the value of the signDeleted property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getSignDeleted() {
	  return signDeleted;
   }

   /**
	* Sets the value of the signDeleted property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setSignDeleted(JAXBElement<BigInteger> value) {
	  this.signDeleted = value;
   }

   /**
	* Gets the value of the route property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RRoute }{@code >}
	*/
   public JAXBElement<RRoute> getRoute() {
	  return route;
   }

   /**
	* Sets the value of the route property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RRoute }{@code >}
	*/
   public void setRoute(JAXBElement<RRoute> value) {
	  this.route = value;
   }

   /**
	* Gets the value of the startDate property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
	*/
   public JAXBElement<XMLGregorianCalendar> getStartDate() {
	  return startDate;
   }

   /**
	* Sets the value of the startDate property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
	*/
   public void setStartDate(JAXBElement<XMLGregorianCalendar> value) {
	  this.startDate = value;
   }

   /**
	* Gets the value of the endDate property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
	*/
   public JAXBElement<XMLGregorianCalendar> getEndDate() {
	  return endDate;
   }

   /**
	* Sets the value of the endDate property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
	*/
   public void setEndDate(JAXBElement<XMLGregorianCalendar> value) {
	  this.endDate = value;
   }

   /**
	* Gets the value of the type property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RRouteVariantType }{@code >}
	*/
   public JAXBElement<RRouteVariantType> getType() {
	  return type;
   }

   /**
	* Sets the value of the type property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RRouteVariantType }{@code >}
	*/
   public void setType(JAXBElement<RRouteVariantType> value) {
	  this.type = value;
   }

   /**
	* Gets the value of the order property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link ROrder }{@code >}
	*/
   public JAXBElement<ROrder> getOrder() {
	  return order;
   }

   /**
	* Sets the value of the order property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link ROrder }{@code >}
	*/
   public void setOrder(JAXBElement<ROrder> value) {
	  this.order = value;
   }

   /**
	* Gets the value of the comment property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getComment() {
	  return comment;
   }

   /**
	* Sets the value of the comment property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setComment(JAXBElement<String> value) {
	  this.comment = value;
   }

}
