//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * Траектории маршрутов
 * <p>
 * <p>
 * <p>Java class for TRouteTrajectory complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TRouteTrajectory">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://mappl.ru/2015/XMLSchema/GISMGT}TGISDictionaryObject"/>
 *         &lt;element name="routeRound" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRouteRound" minOccurs="0"/>
 *         &lt;element name="routeNullRound" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRouteNullRound" minOccurs="0"/>
 *         &lt;element name="trajectoryType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRouteTrajectoryType" minOccurs="0"/>
 *         &lt;element name="regions" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="region" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRegion" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="graphSections" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="linkedGraphSection" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRouteTrajectories2GraphSections" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="stopPlaces" minOccurs="0">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="linkedStopPlace" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRouteTrajectories2StopPlaces" maxOccurs="unbounded"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *         &lt;element name="length" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TLength" minOccurs="0"/>
 *         &lt;element name="fixedLength" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TLength" minOccurs="0"/>
 *         &lt;element name="specification" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSpecification" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TRouteTrajectory", propOrder = {
	"muid",
	"version",
	"signDeleted",
	"wktGeom",
	"routeRound",
	"routeNullRound",
	"trajectoryType",
	"regions",
	"graphSections",
	"stopPlaces",
	"length",
	"fixedLength",
	"specification"
})
public class TRouteTrajectory {

   @XmlElement(required = true)
   protected String muid;
   @XmlElement(defaultValue = "1")
   protected BigInteger version;
   @XmlElementRef(name = "signDeleted", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> signDeleted;
   @XmlElementRef(name = "wkt_geom", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> wktGeom;
   @XmlElementRef(name = "routeRound", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RRouteRound> routeRound;
   @XmlElementRef(name = "routeNullRound", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RRouteNullRound> routeNullRound;
   @XmlElementRef(name = "trajectoryType", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RRouteTrajectoryType> trajectoryType;
   protected TRouteTrajectory.Regions regions;
   protected TRouteTrajectory.GraphSections graphSections;
   protected TRouteTrajectory.StopPlaces stopPlaces;
   @XmlElementRef(name = "length", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Float> length;
   @XmlElementRef(name = "fixedLength", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Float> fixedLength;
   @XmlElementRef(name = "specification", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> specification;

   /**
	* Gets the value of the muid property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getMuid() {
	  return muid;
   }

   /**
	* Sets the value of the muid property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setMuid(String value) {
	  this.muid = value;
   }

   /**
	* Gets the value of the version property.
	*
	* @return possible object is
	* {@link BigInteger }
	*/
   public BigInteger getVersion() {
	  return version;
   }

   /**
	* Sets the value of the version property.
	*
	* @param value allowed object is
	*              {@link BigInteger }
	*/
   public void setVersion(BigInteger value) {
	  this.version = value;
   }

   /**
	* Gets the value of the signDeleted property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getSignDeleted() {
	  return signDeleted;
   }

   /**
	* Sets the value of the signDeleted property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setSignDeleted(JAXBElement<BigInteger> value) {
	  this.signDeleted = value;
   }

   /**
	* Gets the value of the wktGeom property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getWktGeom() {
	  return wktGeom;
   }

   /**
	* Sets the value of the wktGeom property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setWktGeom(JAXBElement<String> value) {
	  this.wktGeom = value;
   }

   /**
	* Gets the value of the routeRound property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RRouteRound }{@code >}
	*/
   public JAXBElement<RRouteRound> getRouteRound() {
	  return routeRound;
   }

   /**
	* Sets the value of the routeRound property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RRouteRound }{@code >}
	*/
   public void setRouteRound(JAXBElement<RRouteRound> value) {
	  this.routeRound = value;
   }

   /**
	* Gets the value of the routeNullRound property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RRouteNullRound }{@code >}
	*/
   public JAXBElement<RRouteNullRound> getRouteNullRound() {
	  return routeNullRound;
   }

   /**
	* Sets the value of the routeNullRound property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RRouteNullRound }{@code >}
	*/
   public void setRouteNullRound(JAXBElement<RRouteNullRound> value) {
	  this.routeNullRound = value;
   }

   /**
	* Gets the value of the trajectoryType property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RRouteTrajectoryType }{@code >}
	*/
   public JAXBElement<RRouteTrajectoryType> getTrajectoryType() {
	  return trajectoryType;
   }

   /**
	* Sets the value of the trajectoryType property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RRouteTrajectoryType }{@code >}
	*/
   public void setTrajectoryType(JAXBElement<RRouteTrajectoryType> value) {
	  this.trajectoryType = value;
   }

   /**
	* Gets the value of the regions property.
	*
	* @return possible object is
	* {@link TRouteTrajectory.Regions }
	*/
   public TRouteTrajectory.Regions getRegions() {
	  return regions;
   }

   /**
	* Sets the value of the regions property.
	*
	* @param value allowed object is
	*              {@link TRouteTrajectory.Regions }
	*/
   public void setRegions(TRouteTrajectory.Regions value) {
	  this.regions = value;
   }

   /**
	* Gets the value of the graphSections property.
	*
	* @return possible object is
	* {@link TRouteTrajectory.GraphSections }
	*/
   public TRouteTrajectory.GraphSections getGraphSections() {
	  return graphSections;
   }

   /**
	* Sets the value of the graphSections property.
	*
	* @param value allowed object is
	*              {@link TRouteTrajectory.GraphSections }
	*/
   public void setGraphSections(TRouteTrajectory.GraphSections value) {
	  this.graphSections = value;
   }

   /**
	* Gets the value of the stopPlaces property.
	*
	* @return possible object is
	* {@link TRouteTrajectory.StopPlaces }
	*/
   public TRouteTrajectory.StopPlaces getStopPlaces() {
	  return stopPlaces;
   }

   /**
	* Sets the value of the stopPlaces property.
	*
	* @param value allowed object is
	*              {@link TRouteTrajectory.StopPlaces }
	*/
   public void setStopPlaces(TRouteTrajectory.StopPlaces value) {
	  this.stopPlaces = value;
   }

   /**
	* Gets the value of the length property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public JAXBElement<Float> getLength() {
	  return length;
   }

   /**
	* Sets the value of the length property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public void setLength(JAXBElement<Float> value) {
	  this.length = value;
   }

   /**
	* Gets the value of the fixedLength property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public JAXBElement<Float> getFixedLength() {
	  return fixedLength;
   }

   /**
	* Sets the value of the fixedLength property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public void setFixedLength(JAXBElement<Float> value) {
	  this.fixedLength = value;
   }

   /**
	* Gets the value of the specification property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getSpecification() {
	  return specification;
   }

   /**
	* Sets the value of the specification property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setSpecification(JAXBElement<String> value) {
	  this.specification = value;
   }


   /**
	* <p>Java class for anonymous complex type.
	* <p>
	* <p>The following schema fragment specifies the expected content contained within this class.
	* <p>
	* <pre>
	* &lt;complexType>
	*   &lt;complexContent>
	*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	*       &lt;sequence>
	*         &lt;element name="linkedGraphSection" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRouteTrajectories2GraphSections" maxOccurs="unbounded"/>
	*       &lt;/sequence>
	*     &lt;/restriction>
	*   &lt;/complexContent>
	* &lt;/complexType>
	* </pre>
	*/
   @XmlAccessorType(XmlAccessType.FIELD)
   @XmlType(name = "", propOrder = {
	   "linkedGraphSections"
   })
   public static class GraphSections {

	  @XmlElement(name = "linkedGraphSection", required = true, nillable = true)
	  protected List<RRouteTrajectories2GraphSections> linkedGraphSections;

	  /**
	   * Gets the value of the linkedGraphSections property.
	   * <p>
	   * <p>
	   * This accessor method returns a reference to the live list,
	   * not a snapshot. Therefore any modification you make to the
	   * returned list will be present inside the JAXB object.
	   * This is why there is not a <CODE>set</CODE> method for the linkedGraphSections property.
	   * <p>
	   * <p>
	   * For example, to add a new item, do as follows:
	   * <pre>
	   *    getLinkedGraphSections().add(newItem);
	   * </pre>
	   * <p>
	   * <p>
	   * <p>
	   * Objects of the following type(s) are allowed in the list
	   * {@link RRouteTrajectories2GraphSections }
	   */
	  public List<RRouteTrajectories2GraphSections> getLinkedGraphSections() {
		 if (linkedGraphSections == null) {
			linkedGraphSections = new ArrayList<RRouteTrajectories2GraphSections>();
		 }
		 return this.linkedGraphSections;
	  }

   }


   /**
	* список регионов
	* <p>
	* <p>
	* <p>Java class for anonymous complex type.
	* <p>
	* <p>The following schema fragment specifies the expected content contained within this class.
	* <p>
	* <pre>
	* &lt;complexType>
	*   &lt;complexContent>
	*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	*       &lt;sequence>
	*         &lt;element name="region" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRegion" maxOccurs="unbounded"/>
	*       &lt;/sequence>
	*     &lt;/restriction>
	*   &lt;/complexContent>
	* &lt;/complexType>
	* </pre>
	*/
   @XmlAccessorType(XmlAccessType.FIELD)
   @XmlType(name = "", propOrder = {
	   "regions"
   })
   public static class Regions {

	  @XmlElement(name = "region", required = true, nillable = true)
	  protected List<RRegion> regions;

	  /**
	   * Gets the value of the regions property.
	   * <p>
	   * <p>
	   * This accessor method returns a reference to the live list,
	   * not a snapshot. Therefore any modification you make to the
	   * returned list will be present inside the JAXB object.
	   * This is why there is not a <CODE>set</CODE> method for the regions property.
	   * <p>
	   * <p>
	   * For example, to add a new item, do as follows:
	   * <pre>
	   *    getRegions().add(newItem);
	   * </pre>
	   * <p>
	   * <p>
	   * <p>
	   * Objects of the following type(s) are allowed in the list
	   * {@link RRegion }
	   */
	  public List<RRegion> getRegions() {
		 if (regions == null) {
			regions = new ArrayList<RRegion>();
		 }
		 return this.regions;
	  }

   }


   /**
	* <p>Java class for anonymous complex type.
	* <p>
	* <p>The following schema fragment specifies the expected content contained within this class.
	* <p>
	* <pre>
	* &lt;complexType>
	*   &lt;complexContent>
	*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	*       &lt;sequence>
	*         &lt;element name="linkedStopPlace" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRouteTrajectories2StopPlaces" maxOccurs="unbounded"/>
	*       &lt;/sequence>
	*     &lt;/restriction>
	*   &lt;/complexContent>
	* &lt;/complexType>
	* </pre>
	*/
   @XmlAccessorType(XmlAccessType.FIELD)
   @XmlType(name = "", propOrder = {
	   "linkedStopPlaces"
   })
   public static class StopPlaces {

	  @XmlElement(name = "linkedStopPlace", required = true, nillable = true)
	  protected List<RRouteTrajectories2StopPlaces> linkedStopPlaces;

	  /**
	   * Gets the value of the linkedStopPlaces property.
	   * <p>
	   * <p>
	   * This accessor method returns a reference to the live list,
	   * not a snapshot. Therefore any modification you make to the
	   * returned list will be present inside the JAXB object.
	   * This is why there is not a <CODE>set</CODE> method for the linkedStopPlaces property.
	   * <p>
	   * <p>
	   * For example, to add a new item, do as follows:
	   * <pre>
	   *    getLinkedStopPlaces().add(newItem);
	   * </pre>
	   * <p>
	   * <p>
	   * <p>
	   * Objects of the following type(s) are allowed in the list
	   * {@link RRouteTrajectories2StopPlaces }
	   */
	  public List<RRouteTrajectories2StopPlaces> getLinkedStopPlaces() {
		 if (linkedStopPlaces == null) {
			linkedStopPlaces = new ArrayList<RRouteTrajectories2StopPlaces>();
		 }
		 return this.linkedStopPlaces;
	  }

   }

}
