//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;
import java.math.BigInteger;


/**
 * Места остановки транспорта (места посадки-высадки)
 * <p>
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;tags xmlns="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:gismgt="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:p578540_="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:p729618_="http://java.sun.com/xml/ns/jaxb" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;&lt;tag&gt;mtrans&lt;/tag&gt;&lt;/tags&gt;
 * </pre>
 * <p>
 * <p>
 * <p>Java class for TStopPlace complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TStopPlace">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://mappl.ru/2015/XMLSchema/GISMGT}TGISDictionaryObject"/>
 *         &lt;element name="suffix" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSuffix" minOccurs="0"/>
 *         &lt;element name="stop" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStop" minOccurs="0"/>
 *         &lt;element name="order" type="{http://mappl.ru/2015/XMLSchema/GISMGT}ROrder" minOccurs="0"/>
 *         &lt;element name="startDate" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TDate" minOccurs="0"/>
 *         &lt;element name="changeDate" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TDate" minOccurs="0"/>
 *         &lt;element name="endDate" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TDate" minOccurs="0"/>
 *         &lt;element name="state" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStopState" minOccurs="0"/>
 *         &lt;element name="mode" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStopMode" minOccurs="0"/>
 *         &lt;element name="photo" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TPhoto" minOccurs="0"/>
 *         &lt;element name="isTechnical" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSign" minOccurs="0"/>
 *         &lt;element name="hasFacilitiesForDisabled" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSign" minOccurs="0"/>
 *         &lt;element name="hasBay" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSign" minOccurs="0"/>
 *         &lt;group ref="{http://mappl.ru/2015/XMLSchema/GISMGT}THasTransportSigns"/>
 *         &lt;element name="hasDisplayPanel" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSign" minOccurs="0"/>
 *         &lt;element name="displayPanelType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TDisplayPanelInfo" minOccurs="0"/>
 *         &lt;element name="displayPanelIMEI" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TDisplayPanelInfo" minOccurs="0"/>
 *         &lt;element name="displayPanelSim" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TDisplayPanelInfo" minOccurs="0"/>
 *         &lt;element name="displayPanelASUT" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TDisplayPanelInfo" minOccurs="0"/>
 *         &lt;element name="building" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RBuilding" minOccurs="0"/>
 *         &lt;element name="buildingDistance" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TLength" minOccurs="0"/>
 *         &lt;element name="buildingAddressString" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TAddressString" minOccurs="0"/>
 *         &lt;element name="graphSection" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RGraphSection" minOccurs="0"/>
 *         &lt;element name="graphSectionOffset" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TLength" minOccurs="0"/>
 *         &lt;element name="graphTramSection" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RGraphSection" minOccurs="0"/>
 *         &lt;element name="graphTramSectionOffset" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TLength" minOccurs="0"/>
 *         &lt;element name="comment" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComment" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TStopPlace", propOrder = {
	"muid",
	"version",
	"signDeleted",
	"wktGeom",
	"suffix",
	"stop",
	"order",
	"startDate",
	"changeDate",
	"endDate",
	"state",
	"mode",
	"photo",
	"isTechnical",
	"hasFacilitiesForDisabled",
	"hasBay",
	"hasBus",
	"hasTrolley",
	"hasTram",
	"hasSpeedTram",
	"hasDisplayPanel",
	"displayPanelType",
	"displayPanelIMEI",
	"displayPanelSim",
	"displayPanelASUT",
	"building",
	"buildingDistance",
	"buildingAddressString",
	"graphSection",
	"graphSectionOffset",
	"graphTramSection",
	"graphTramSectionOffset",
	"comment"
})
public class TStopPlace {

   @XmlElement(required = true)
   protected String muid;
   @XmlElement(defaultValue = "1")
   protected BigInteger version;
   @XmlElementRef(name = "signDeleted", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> signDeleted;
   @XmlElementRef(name = "wkt_geom", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> wktGeom;
   @XmlElementRef(name = "suffix", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> suffix;
   @XmlElementRef(name = "stop", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RStop> stop;
   @XmlElementRef(name = "order", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<ROrder> order;
   @XmlElementRef(name = "startDate", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<XMLGregorianCalendar> startDate;
   @XmlElementRef(name = "changeDate", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<XMLGregorianCalendar> changeDate;
   @XmlElementRef(name = "endDate", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<XMLGregorianCalendar> endDate;
   @XmlElementRef(name = "state", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RStopState> state;
   @XmlElementRef(name = "mode", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RStopMode> mode;
   @XmlElementRef(name = "photo", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<byte[]> photo;
   @XmlElementRef(name = "isTechnical", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> isTechnical;
   @XmlElementRef(name = "hasFacilitiesForDisabled", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasFacilitiesForDisabled;
   @XmlElementRef(name = "hasBay", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasBay;
   @XmlElementRef(name = "hasBus", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasBus;
   @XmlElementRef(name = "hasTrolley", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasTrolley;
   @XmlElementRef(name = "hasTram", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasTram;
   @XmlElementRef(name = "hasSpeedTram", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasSpeedTram;
   @XmlElementRef(name = "hasDisplayPanel", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasDisplayPanel;
   @XmlElementRef(name = "displayPanelType", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> displayPanelType;
   @XmlElementRef(name = "displayPanelIMEI", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> displayPanelIMEI;
   @XmlElementRef(name = "displayPanelSim", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> displayPanelSim;
   @XmlElementRef(name = "displayPanelASUT", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> displayPanelASUT;
   @XmlElementRef(name = "building", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RBuilding> building;
   @XmlElementRef(name = "buildingDistance", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Float> buildingDistance;
   @XmlElementRef(name = "buildingAddressString", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> buildingAddressString;
   @XmlElementRef(name = "graphSection", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RGraphSection> graphSection;
   @XmlElementRef(name = "graphSectionOffset", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Float> graphSectionOffset;
   @XmlElementRef(name = "graphTramSection", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RGraphSection> graphTramSection;
   @XmlElementRef(name = "graphTramSectionOffset", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Float> graphTramSectionOffset;
   @XmlElementRef(name = "comment", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> comment;

   /**
	* Gets the value of the muid property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getMuid() {
	  return muid;
   }

   /**
	* Sets the value of the muid property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setMuid(String value) {
	  this.muid = value;
   }

   /**
	* Gets the value of the version property.
	*
	* @return possible object is
	* {@link BigInteger }
	*/
   public BigInteger getVersion() {
	  return version;
   }

   /**
	* Sets the value of the version property.
	*
	* @param value allowed object is
	*              {@link BigInteger }
	*/
   public void setVersion(BigInteger value) {
	  this.version = value;
   }

   /**
	* Gets the value of the signDeleted property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getSignDeleted() {
	  return signDeleted;
   }

   /**
	* Sets the value of the signDeleted property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setSignDeleted(JAXBElement<BigInteger> value) {
	  this.signDeleted = value;
   }

   /**
	* Gets the value of the wktGeom property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getWktGeom() {
	  return wktGeom;
   }

   /**
	* Sets the value of the wktGeom property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setWktGeom(JAXBElement<String> value) {
	  this.wktGeom = value;
   }

   /**
	* Gets the value of the suffix property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getSuffix() {
	  return suffix;
   }

   /**
	* Sets the value of the suffix property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setSuffix(JAXBElement<String> value) {
	  this.suffix = value;
   }

   /**
	* Gets the value of the stop property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RStop }{@code >}
	*/
   public JAXBElement<RStop> getStop() {
	  return stop;
   }

   /**
	* Sets the value of the stop property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RStop }{@code >}
	*/
   public void setStop(JAXBElement<RStop> value) {
	  this.stop = value;
   }

   /**
	* Gets the value of the order property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link ROrder }{@code >}
	*/
   public JAXBElement<ROrder> getOrder() {
	  return order;
   }

   /**
	* Sets the value of the order property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link ROrder }{@code >}
	*/
   public void setOrder(JAXBElement<ROrder> value) {
	  this.order = value;
   }

   /**
	* Gets the value of the startDate property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
	*/
   public JAXBElement<XMLGregorianCalendar> getStartDate() {
	  return startDate;
   }

   /**
	* Sets the value of the startDate property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
	*/
   public void setStartDate(JAXBElement<XMLGregorianCalendar> value) {
	  this.startDate = value;
   }

   /**
	* Gets the value of the changeDate property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
	*/
   public JAXBElement<XMLGregorianCalendar> getChangeDate() {
	  return changeDate;
   }

   /**
	* Sets the value of the changeDate property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
	*/
   public void setChangeDate(JAXBElement<XMLGregorianCalendar> value) {
	  this.changeDate = value;
   }

   /**
	* Gets the value of the endDate property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
	*/
   public JAXBElement<XMLGregorianCalendar> getEndDate() {
	  return endDate;
   }

   /**
	* Sets the value of the endDate property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link XMLGregorianCalendar }{@code >}
	*/
   public void setEndDate(JAXBElement<XMLGregorianCalendar> value) {
	  this.endDate = value;
   }

   /**
	* Gets the value of the state property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RStopState }{@code >}
	*/
   public JAXBElement<RStopState> getState() {
	  return state;
   }

   /**
	* Sets the value of the state property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RStopState }{@code >}
	*/
   public void setState(JAXBElement<RStopState> value) {
	  this.state = value;
   }

   /**
	* Gets the value of the mode property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RStopMode }{@code >}
	*/
   public JAXBElement<RStopMode> getMode() {
	  return mode;
   }

   /**
	* Sets the value of the mode property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RStopMode }{@code >}
	*/
   public void setMode(JAXBElement<RStopMode> value) {
	  this.mode = value;
   }

   /**
	* Gets the value of the photo property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link byte[]}{@code >}
	*/
   public JAXBElement<byte[]> getPhoto() {
	  return photo;
   }

   /**
	* Sets the value of the photo property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link byte[]}{@code >}
	*/
   public void setPhoto(JAXBElement<byte[]> value) {
	  this.photo = value;
   }

   /**
	* Gets the value of the isTechnical property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getIsTechnical() {
	  return isTechnical;
   }

   /**
	* Sets the value of the isTechnical property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setIsTechnical(JAXBElement<BigInteger> value) {
	  this.isTechnical = value;
   }

   /**
	* Gets the value of the hasFacilitiesForDisabled property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasFacilitiesForDisabled() {
	  return hasFacilitiesForDisabled;
   }

   /**
	* Sets the value of the hasFacilitiesForDisabled property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasFacilitiesForDisabled(JAXBElement<BigInteger> value) {
	  this.hasFacilitiesForDisabled = value;
   }

   /**
	* Gets the value of the hasBay property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasBay() {
	  return hasBay;
   }

   /**
	* Sets the value of the hasBay property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasBay(JAXBElement<BigInteger> value) {
	  this.hasBay = value;
   }

   /**
	* Gets the value of the hasBus property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasBus() {
	  return hasBus;
   }

   /**
	* Sets the value of the hasBus property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasBus(JAXBElement<BigInteger> value) {
	  this.hasBus = value;
   }

   /**
	* Gets the value of the hasTrolley property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasTrolley() {
	  return hasTrolley;
   }

   /**
	* Sets the value of the hasTrolley property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasTrolley(JAXBElement<BigInteger> value) {
	  this.hasTrolley = value;
   }

   /**
	* Gets the value of the hasTram property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasTram() {
	  return hasTram;
   }

   /**
	* Sets the value of the hasTram property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasTram(JAXBElement<BigInteger> value) {
	  this.hasTram = value;
   }

   /**
	* Gets the value of the hasSpeedTram property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasSpeedTram() {
	  return hasSpeedTram;
   }

   /**
	* Sets the value of the hasSpeedTram property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasSpeedTram(JAXBElement<BigInteger> value) {
	  this.hasSpeedTram = value;
   }

   /**
	* Gets the value of the hasDisplayPanel property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasDisplayPanel() {
	  return hasDisplayPanel;
   }

   /**
	* Sets the value of the hasDisplayPanel property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasDisplayPanel(JAXBElement<BigInteger> value) {
	  this.hasDisplayPanel = value;
   }

   /**
	* Gets the value of the displayPanelType property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getDisplayPanelType() {
	  return displayPanelType;
   }

   /**
	* Sets the value of the displayPanelType property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setDisplayPanelType(JAXBElement<String> value) {
	  this.displayPanelType = value;
   }

   /**
	* Gets the value of the displayPanelIMEI property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getDisplayPanelIMEI() {
	  return displayPanelIMEI;
   }

   /**
	* Sets the value of the displayPanelIMEI property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setDisplayPanelIMEI(JAXBElement<String> value) {
	  this.displayPanelIMEI = value;
   }

   /**
	* Gets the value of the displayPanelSim property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getDisplayPanelSim() {
	  return displayPanelSim;
   }

   /**
	* Sets the value of the displayPanelSim property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setDisplayPanelSim(JAXBElement<String> value) {
	  this.displayPanelSim = value;
   }

   /**
	* Gets the value of the displayPanelASUT property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getDisplayPanelASUT() {
	  return displayPanelASUT;
   }

   /**
	* Sets the value of the displayPanelASUT property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setDisplayPanelASUT(JAXBElement<String> value) {
	  this.displayPanelASUT = value;
   }

   /**
	* Gets the value of the building property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RBuilding }{@code >}
	*/
   public JAXBElement<RBuilding> getBuilding() {
	  return building;
   }

   /**
	* Sets the value of the building property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RBuilding }{@code >}
	*/
   public void setBuilding(JAXBElement<RBuilding> value) {
	  this.building = value;
   }

   /**
	* Gets the value of the buildingDistance property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public JAXBElement<Float> getBuildingDistance() {
	  return buildingDistance;
   }

   /**
	* Sets the value of the buildingDistance property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public void setBuildingDistance(JAXBElement<Float> value) {
	  this.buildingDistance = value;
   }

   /**
	* Gets the value of the buildingAddressString property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getBuildingAddressString() {
	  return buildingAddressString;
   }

   /**
	* Sets the value of the buildingAddressString property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setBuildingAddressString(JAXBElement<String> value) {
	  this.buildingAddressString = value;
   }

   /**
	* Gets the value of the graphSection property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RGraphSection }{@code >}
	*/
   public JAXBElement<RGraphSection> getGraphSection() {
	  return graphSection;
   }

   /**
	* Sets the value of the graphSection property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RGraphSection }{@code >}
	*/
   public void setGraphSection(JAXBElement<RGraphSection> value) {
	  this.graphSection = value;
   }

   /**
	* Gets the value of the graphSectionOffset property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public JAXBElement<Float> getGraphSectionOffset() {
	  return graphSectionOffset;
   }

   /**
	* Sets the value of the graphSectionOffset property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public void setGraphSectionOffset(JAXBElement<Float> value) {
	  this.graphSectionOffset = value;
   }

   /**
	* Gets the value of the graphTramSection property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RGraphSection }{@code >}
	*/
   public JAXBElement<RGraphSection> getGraphTramSection() {
	  return graphTramSection;
   }

   /**
	* Sets the value of the graphTramSection property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RGraphSection }{@code >}
	*/
   public void setGraphTramSection(JAXBElement<RGraphSection> value) {
	  this.graphTramSection = value;
   }

   /**
	* Gets the value of the graphTramSectionOffset property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public JAXBElement<Float> getGraphTramSectionOffset() {
	  return graphTramSectionOffset;
   }

   /**
	* Sets the value of the graphTramSectionOffset property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public void setGraphTramSectionOffset(JAXBElement<Float> value) {
	  this.graphTramSectionOffset = value;
   }

   /**
	* Gets the value of the comment property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getComment() {
	  return comment;
   }

   /**
	* Sets the value of the comment property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setComment(JAXBElement<String> value) {
	  this.comment = value;
   }

}
