//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;
import java.util.ArrayList;
import java.util.List;


/**
 * Остановочные павильоны
 * <p>
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;tags xmlns="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:gismgt="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:p578540_="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:p729618_="http://java.sun.com/xml/ns/jaxb" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;&lt;tag&gt;mtrans&lt;/tag&gt;&lt;/tags&gt;
 * </pre>
 * <p>
 * <p>
 * <p>Java class for TStopPavilion complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TStopPavilion">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://mappl.ru/2015/XMLSchema/GISMGT}TGISDictionaryObject"/>
 *         &lt;element name="inventoryDistrict" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TInt2" minOccurs="0"/>
 *         &lt;element name="inventoryYear" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TInt4" minOccurs="0"/>
 *         &lt;element name="inventoryNumber" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TVarchar20" minOccurs="0"/>
 *         &lt;element name="currentStopPavilionInstallation" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStopPavilionInstallation" maxOccurs="unbounded"/>
 *         &lt;element name="stopPavilionType" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStopPavilionType" maxOccurs="unbounded"/>
 *         &lt;element name="balanceOrgatization" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStopPavilionBalanceOrganization" maxOccurs="unbounded"/>
 *         &lt;element name="installOrgatization" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStopPavilionInstallOrganization" maxOccurs="unbounded"/>
 *         &lt;element name="serviceOrgatization" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStopPavilionServiceOrganization" maxOccurs="unbounded"/>
 *         &lt;element name="pavilionState" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStopPavilionState" maxOccurs="unbounded"/>
 *         &lt;element name="isAbsent" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSign" minOccurs="0"/>
 *         &lt;element name="hasElectricity" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSign" minOccurs="0"/>
 *         &lt;element name="comment" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TComment255" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TStopPavilion", propOrder = {
	"muid",
	"version",
	"signDeleted",
	"wktGeom",
	"inventoryDistrict",
	"inventoryYear",
	"inventoryNumber",
	"currentStopPavilionInstallations",
	"stopPavilionTypes",
	"balanceOrgatizations",
	"installOrgatizations",
	"serviceOrgatizations",
	"pavilionStates",
	"isAbsent",
	"hasElectricity",
	"comment"
})
public class TStopPavilion {

   @XmlElement(required = true)
   protected String muid;
   @XmlElement(defaultValue = "1")
   protected BigInteger version;
   @XmlElementRef(name = "signDeleted", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> signDeleted;
   @XmlElementRef(name = "wkt_geom", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> wktGeom;
   @XmlElementRef(name = "inventoryDistrict", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Integer> inventoryDistrict;
   @XmlElementRef(name = "inventoryYear", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> inventoryYear;
   @XmlElementRef(name = "inventoryNumber", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> inventoryNumber;
   @XmlElement(name = "currentStopPavilionInstallation", required = true, nillable = true)
   protected List<RStopPavilionInstallation> currentStopPavilionInstallations;
   @XmlElement(name = "stopPavilionType", required = true, nillable = true)
   protected List<RStopPavilionType> stopPavilionTypes;
   @XmlElement(name = "balanceOrgatization", required = true, nillable = true)
   protected List<RStopPavilionBalanceOrganization> balanceOrgatizations;
   @XmlElement(name = "installOrgatization", required = true, nillable = true)
   protected List<RStopPavilionInstallOrganization> installOrgatizations;
   @XmlElement(name = "serviceOrgatization", required = true, nillable = true)
   protected List<RStopPavilionServiceOrganization> serviceOrgatizations;
   @XmlElement(name = "pavilionState", required = true, nillable = true)
   protected List<RStopPavilionState> pavilionStates;
   @XmlElementRef(name = "isAbsent", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> isAbsent;
   @XmlElementRef(name = "hasElectricity", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasElectricity;
   @XmlElementRef(name = "comment", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> comment;

   /**
	* Gets the value of the muid property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getMuid() {
	  return muid;
   }

   /**
	* Sets the value of the muid property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setMuid(String value) {
	  this.muid = value;
   }

   /**
	* Gets the value of the version property.
	*
	* @return possible object is
	* {@link BigInteger }
	*/
   public BigInteger getVersion() {
	  return version;
   }

   /**
	* Sets the value of the version property.
	*
	* @param value allowed object is
	*              {@link BigInteger }
	*/
   public void setVersion(BigInteger value) {
	  this.version = value;
   }

   /**
	* Gets the value of the signDeleted property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getSignDeleted() {
	  return signDeleted;
   }

   /**
	* Sets the value of the signDeleted property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setSignDeleted(JAXBElement<BigInteger> value) {
	  this.signDeleted = value;
   }

   /**
	* Gets the value of the wktGeom property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getWktGeom() {
	  return wktGeom;
   }

   /**
	* Sets the value of the wktGeom property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setWktGeom(JAXBElement<String> value) {
	  this.wktGeom = value;
   }

   /**
	* Gets the value of the inventoryDistrict property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Integer }{@code >}
	*/
   public JAXBElement<Integer> getInventoryDistrict() {
	  return inventoryDistrict;
   }

   /**
	* Sets the value of the inventoryDistrict property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Integer }{@code >}
	*/
   public void setInventoryDistrict(JAXBElement<Integer> value) {
	  this.inventoryDistrict = value;
   }

   /**
	* Gets the value of the inventoryYear property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getInventoryYear() {
	  return inventoryYear;
   }

   /**
	* Sets the value of the inventoryYear property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setInventoryYear(JAXBElement<BigInteger> value) {
	  this.inventoryYear = value;
   }

   /**
	* Gets the value of the inventoryNumber property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getInventoryNumber() {
	  return inventoryNumber;
   }

   /**
	* Sets the value of the inventoryNumber property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setInventoryNumber(JAXBElement<String> value) {
	  this.inventoryNumber = value;
   }

   /**
	* Gets the value of the currentStopPavilionInstallations property.
	* <p>
	* <p>
	* This accessor method returns a reference to the live list,
	* not a snapshot. Therefore any modification you make to the
	* returned list will be present inside the JAXB object.
	* This is why there is not a <CODE>set</CODE> method for the currentStopPavilionInstallations property.
	* <p>
	* <p>
	* For example, to add a new item, do as follows:
	* <pre>
	*    getCurrentStopPavilionInstallations().add(newItem);
	* </pre>
	* <p>
	* <p>
	* <p>
	* Objects of the following type(s) are allowed in the list
	* {@link RStopPavilionInstallation }
	*/
   public List<RStopPavilionInstallation> getCurrentStopPavilionInstallations() {
	  if (currentStopPavilionInstallations == null) {
		 currentStopPavilionInstallations = new ArrayList<RStopPavilionInstallation>();
	  }
	  return this.currentStopPavilionInstallations;
   }

   /**
	* Gets the value of the stopPavilionTypes property.
	* <p>
	* <p>
	* This accessor method returns a reference to the live list,
	* not a snapshot. Therefore any modification you make to the
	* returned list will be present inside the JAXB object.
	* This is why there is not a <CODE>set</CODE> method for the stopPavilionTypes property.
	* <p>
	* <p>
	* For example, to add a new item, do as follows:
	* <pre>
	*    getStopPavilionTypes().add(newItem);
	* </pre>
	* <p>
	* <p>
	* <p>
	* Objects of the following type(s) are allowed in the list
	* {@link RStopPavilionType }
	*/
   public List<RStopPavilionType> getStopPavilionTypes() {
	  if (stopPavilionTypes == null) {
		 stopPavilionTypes = new ArrayList<RStopPavilionType>();
	  }
	  return this.stopPavilionTypes;
   }

   /**
	* Gets the value of the balanceOrgatizations property.
	* <p>
	* <p>
	* This accessor method returns a reference to the live list,
	* not a snapshot. Therefore any modification you make to the
	* returned list will be present inside the JAXB object.
	* This is why there is not a <CODE>set</CODE> method for the balanceOrgatizations property.
	* <p>
	* <p>
	* For example, to add a new item, do as follows:
	* <pre>
	*    getBalanceOrgatizations().add(newItem);
	* </pre>
	* <p>
	* <p>
	* <p>
	* Objects of the following type(s) are allowed in the list
	* {@link RStopPavilionBalanceOrganization }
	*/
   public List<RStopPavilionBalanceOrganization> getBalanceOrgatizations() {
	  if (balanceOrgatizations == null) {
		 balanceOrgatizations = new ArrayList<RStopPavilionBalanceOrganization>();
	  }
	  return this.balanceOrgatizations;
   }

   /**
	* Gets the value of the installOrgatizations property.
	* <p>
	* <p>
	* This accessor method returns a reference to the live list,
	* not a snapshot. Therefore any modification you make to the
	* returned list will be present inside the JAXB object.
	* This is why there is not a <CODE>set</CODE> method for the installOrgatizations property.
	* <p>
	* <p>
	* For example, to add a new item, do as follows:
	* <pre>
	*    getInstallOrgatizations().add(newItem);
	* </pre>
	* <p>
	* <p>
	* <p>
	* Objects of the following type(s) are allowed in the list
	* {@link RStopPavilionInstallOrganization }
	*/
   public List<RStopPavilionInstallOrganization> getInstallOrgatizations() {
	  if (installOrgatizations == null) {
		 installOrgatizations = new ArrayList<RStopPavilionInstallOrganization>();
	  }
	  return this.installOrgatizations;
   }

   /**
	* Gets the value of the serviceOrgatizations property.
	* <p>
	* <p>
	* This accessor method returns a reference to the live list,
	* not a snapshot. Therefore any modification you make to the
	* returned list will be present inside the JAXB object.
	* This is why there is not a <CODE>set</CODE> method for the serviceOrgatizations property.
	* <p>
	* <p>
	* For example, to add a new item, do as follows:
	* <pre>
	*    getServiceOrgatizations().add(newItem);
	* </pre>
	* <p>
	* <p>
	* <p>
	* Objects of the following type(s) are allowed in the list
	* {@link RStopPavilionServiceOrganization }
	*/
   public List<RStopPavilionServiceOrganization> getServiceOrgatizations() {
	  if (serviceOrgatizations == null) {
		 serviceOrgatizations = new ArrayList<RStopPavilionServiceOrganization>();
	  }
	  return this.serviceOrgatizations;
   }

   /**
	* Gets the value of the pavilionStates property.
	* <p>
	* <p>
	* This accessor method returns a reference to the live list,
	* not a snapshot. Therefore any modification you make to the
	* returned list will be present inside the JAXB object.
	* This is why there is not a <CODE>set</CODE> method for the pavilionStates property.
	* <p>
	* <p>
	* For example, to add a new item, do as follows:
	* <pre>
	*    getPavilionStates().add(newItem);
	* </pre>
	* <p>
	* <p>
	* <p>
	* Objects of the following type(s) are allowed in the list
	* {@link RStopPavilionState }
	*/
   public List<RStopPavilionState> getPavilionStates() {
	  if (pavilionStates == null) {
		 pavilionStates = new ArrayList<RStopPavilionState>();
	  }
	  return this.pavilionStates;
   }

   /**
	* Gets the value of the isAbsent property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getIsAbsent() {
	  return isAbsent;
   }

   /**
	* Sets the value of the isAbsent property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setIsAbsent(JAXBElement<BigInteger> value) {
	  this.isAbsent = value;
   }

   /**
	* Gets the value of the hasElectricity property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasElectricity() {
	  return hasElectricity;
   }

   /**
	* Sets the value of the hasElectricity property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasElectricity(JAXBElement<BigInteger> value) {
	  this.hasElectricity = value;
   }

   /**
	* Gets the value of the comment property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getComment() {
	  return comment;
   }

   /**
	* Sets the value of the comment property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setComment(JAXBElement<String> value) {
	  this.comment = value;
   }

}
