//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * Остановки (остановочные пункты)
 * <p>
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;tags xmlns="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:gismgt="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:p578540_="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:p729618_="http://java.sun.com/xml/ns/jaxb" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;&lt;tag&gt;mtrans&lt;/tag&gt;&lt;/tags&gt;
 * </pre>
 * <p>
 * <p>
 * <p>Java class for TStop complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TStop">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://mappl.ru/2015/XMLSchema/GISMGT}TDictionaryObject"/>
 *         &lt;element name="name" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TName" minOccurs="0"/>
 *         &lt;element name="nameInEnglish" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TName" minOccurs="0"/>
 *         &lt;element name="nameForTermnalPoint" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TName" minOccurs="0"/>
 *         &lt;element name="district" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RDistrict" minOccurs="0"/>
 *         &lt;element name="region" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRegion" minOccurs="0"/>
 *         &lt;element name="street" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStreet" minOccurs="0"/>
 *         &lt;element name="direction" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RMovementDirection" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TStop", propOrder = {
	"muid",
	"version",
	"signDeleted",
	"name",
	"nameInEnglish",
	"nameForTermnalPoint",
	"district",
	"region",
	"street",
	"direction"
})
public class TStop {

   @XmlElement(required = true)
   protected String muid;
   @XmlElement(defaultValue = "1")
   protected BigInteger version;
   @XmlElementRef(name = "signDeleted", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> signDeleted;
   protected String name;
   protected String nameInEnglish;
   protected String nameForTermnalPoint;
   @XmlElementRef(name = "district", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RDistrict> district;
   @XmlElementRef(name = "region", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RRegion> region;
   @XmlElementRef(name = "street", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RStreet> street;
   @XmlElementRef(name = "direction", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RMovementDirection> direction;

   /**
	* Gets the value of the muid property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getMuid() {
	  return muid;
   }

   /**
	* Sets the value of the muid property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setMuid(String value) {
	  this.muid = value;
   }

   /**
	* Gets the value of the version property.
	*
	* @return possible object is
	* {@link BigInteger }
	*/
   public BigInteger getVersion() {
	  return version;
   }

   /**
	* Sets the value of the version property.
	*
	* @param value allowed object is
	*              {@link BigInteger }
	*/
   public void setVersion(BigInteger value) {
	  this.version = value;
   }

   /**
	* Gets the value of the signDeleted property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getSignDeleted() {
	  return signDeleted;
   }

   /**
	* Sets the value of the signDeleted property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setSignDeleted(JAXBElement<BigInteger> value) {
	  this.signDeleted = value;
   }

   /**
	* Gets the value of the name property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getName() {
	  return name;
   }

   /**
	* Sets the value of the name property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setName(String value) {
	  this.name = value;
   }

   /**
	* Gets the value of the nameInEnglish property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getNameInEnglish() {
	  return nameInEnglish;
   }

   /**
	* Sets the value of the nameInEnglish property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setNameInEnglish(String value) {
	  this.nameInEnglish = value;
   }

   /**
	* Gets the value of the nameForTermnalPoint property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getNameForTermnalPoint() {
	  return nameForTermnalPoint;
   }

   /**
	* Sets the value of the nameForTermnalPoint property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setNameForTermnalPoint(String value) {
	  this.nameForTermnalPoint = value;
   }

   /**
	* Gets the value of the district property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RDistrict }{@code >}
	*/
   public JAXBElement<RDistrict> getDistrict() {
	  return district;
   }

   /**
	* Sets the value of the district property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RDistrict }{@code >}
	*/
   public void setDistrict(JAXBElement<RDistrict> value) {
	  this.district = value;
   }

   /**
	* Gets the value of the region property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RRegion }{@code >}
	*/
   public JAXBElement<RRegion> getRegion() {
	  return region;
   }

   /**
	* Sets the value of the region property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RRegion }{@code >}
	*/
   public void setRegion(JAXBElement<RRegion> value) {
	  this.region = value;
   }

   /**
	* Gets the value of the street property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RStreet }{@code >}
	*/
   public JAXBElement<RStreet> getStreet() {
	  return street;
   }

   /**
	* Sets the value of the street property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RStreet }{@code >}
	*/
   public void setStreet(JAXBElement<RStreet> value) {
	  this.street = value;
   }

   /**
	* Gets the value of the direction property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RMovementDirection }{@code >}
	*/
   public JAXBElement<RMovementDirection> getDirection() {
	  return direction;
   }

   /**
	* Sets the value of the direction property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RMovementDirection }{@code >}
	*/
   public void setDirection(JAXBElement<RMovementDirection> value) {
	  this.direction = value;
   }

}
