//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * Отстойные площадки
 * <p>
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;tags xmlns="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:gismgt="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:p578540_="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:p729618_="http://java.sun.com/xml/ns/jaxb" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;&lt;tag&gt;mtrans&lt;/tag&gt;&lt;/tags&gt;
 * </pre>
 * <p>
 * <p>
 * <p>Java class for TTransportParking complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TTransportParking">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://mappl.ru/2015/XMLSchema/GISMGT}TGISDictionaryObject"/>
 *         &lt;element name="name" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TName" minOccurs="0"/>
 *         &lt;element name="street" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RStreet" minOccurs="0"/>
 *         &lt;element name="building" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RBuilding" minOccurs="0"/>
 *         &lt;element name="addressString" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TAddressString" minOccurs="0"/>
 *         &lt;element name="phone" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TPhone" minOccurs="0"/>
 *         &lt;element name="park" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RPark" minOccurs="0"/>
 *         &lt;element name="square" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TArea" minOccurs="0"/>
 *         &lt;element name="capacity" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TCapacity" minOccurs="0"/>
 *         &lt;element name="graphSection" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RGraphSection" minOccurs="0"/>
 *         &lt;element name="graphSectionOffset" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TLength" minOccurs="0"/>
 *         &lt;group ref="{http://mappl.ru/2015/XMLSchema/GISMGT}THasTransportSigns"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TTransportParking", propOrder = {
	"muid",
	"version",
	"signDeleted",
	"wktGeom",
	"name",
	"street",
	"building",
	"addressString",
	"phone",
	"park",
	"square",
	"capacity",
	"graphSection",
	"graphSectionOffset",
	"hasBus",
	"hasTrolley",
	"hasTram",
	"hasSpeedTram"
})
public class TTransportParking {

   @XmlElement(required = true)
   protected String muid;
   @XmlElement(defaultValue = "1")
   protected BigInteger version;
   @XmlElementRef(name = "signDeleted", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> signDeleted;
   @XmlElementRef(name = "wkt_geom", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> wktGeom;
   protected String name;
   @XmlElementRef(name = "street", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RStreet> street;
   @XmlElementRef(name = "building", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RBuilding> building;
   @XmlElementRef(name = "addressString", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> addressString;
   @XmlElementRef(name = "phone", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> phone;
   @XmlElementRef(name = "park", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RPark> park;
   @XmlElementRef(name = "square", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Float> square;
   @XmlElementRef(name = "capacity", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Long> capacity;
   @XmlElementRef(name = "graphSection", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RGraphSection> graphSection;
   @XmlElementRef(name = "graphSectionOffset", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Float> graphSectionOffset;
   @XmlElementRef(name = "hasBus", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasBus;
   @XmlElementRef(name = "hasTrolley", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasTrolley;
   @XmlElementRef(name = "hasTram", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasTram;
   @XmlElementRef(name = "hasSpeedTram", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasSpeedTram;

   /**
	* Gets the value of the muid property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getMuid() {
	  return muid;
   }

   /**
	* Sets the value of the muid property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setMuid(String value) {
	  this.muid = value;
   }

   /**
	* Gets the value of the version property.
	*
	* @return possible object is
	* {@link BigInteger }
	*/
   public BigInteger getVersion() {
	  return version;
   }

   /**
	* Sets the value of the version property.
	*
	* @param value allowed object is
	*              {@link BigInteger }
	*/
   public void setVersion(BigInteger value) {
	  this.version = value;
   }

   /**
	* Gets the value of the signDeleted property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getSignDeleted() {
	  return signDeleted;
   }

   /**
	* Sets the value of the signDeleted property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setSignDeleted(JAXBElement<BigInteger> value) {
	  this.signDeleted = value;
   }

   /**
	* Gets the value of the wktGeom property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getWktGeom() {
	  return wktGeom;
   }

   /**
	* Sets the value of the wktGeom property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setWktGeom(JAXBElement<String> value) {
	  this.wktGeom = value;
   }

   /**
	* Gets the value of the name property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getName() {
	  return name;
   }

   /**
	* Sets the value of the name property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setName(String value) {
	  this.name = value;
   }

   /**
	* Gets the value of the street property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RStreet }{@code >}
	*/
   public JAXBElement<RStreet> getStreet() {
	  return street;
   }

   /**
	* Sets the value of the street property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RStreet }{@code >}
	*/
   public void setStreet(JAXBElement<RStreet> value) {
	  this.street = value;
   }

   /**
	* Gets the value of the building property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RBuilding }{@code >}
	*/
   public JAXBElement<RBuilding> getBuilding() {
	  return building;
   }

   /**
	* Sets the value of the building property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RBuilding }{@code >}
	*/
   public void setBuilding(JAXBElement<RBuilding> value) {
	  this.building = value;
   }

   /**
	* Gets the value of the addressString property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getAddressString() {
	  return addressString;
   }

   /**
	* Sets the value of the addressString property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setAddressString(JAXBElement<String> value) {
	  this.addressString = value;
   }

   /**
	* Gets the value of the phone property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getPhone() {
	  return phone;
   }

   /**
	* Sets the value of the phone property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setPhone(JAXBElement<String> value) {
	  this.phone = value;
   }

   /**
	* Gets the value of the park property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RPark }{@code >}
	*/
   public JAXBElement<RPark> getPark() {
	  return park;
   }

   /**
	* Sets the value of the park property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RPark }{@code >}
	*/
   public void setPark(JAXBElement<RPark> value) {
	  this.park = value;
   }

   /**
	* Gets the value of the square property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public JAXBElement<Float> getSquare() {
	  return square;
   }

   /**
	* Sets the value of the square property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public void setSquare(JAXBElement<Float> value) {
	  this.square = value;
   }

   /**
	* Gets the value of the capacity property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Long }{@code >}
	*/
   public JAXBElement<Long> getCapacity() {
	  return capacity;
   }

   /**
	* Sets the value of the capacity property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Long }{@code >}
	*/
   public void setCapacity(JAXBElement<Long> value) {
	  this.capacity = value;
   }

   /**
	* Gets the value of the graphSection property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RGraphSection }{@code >}
	*/
   public JAXBElement<RGraphSection> getGraphSection() {
	  return graphSection;
   }

   /**
	* Sets the value of the graphSection property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RGraphSection }{@code >}
	*/
   public void setGraphSection(JAXBElement<RGraphSection> value) {
	  this.graphSection = value;
   }

   /**
	* Gets the value of the graphSectionOffset property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public JAXBElement<Float> getGraphSectionOffset() {
	  return graphSectionOffset;
   }

   /**
	* Sets the value of the graphSectionOffset property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public void setGraphSectionOffset(JAXBElement<Float> value) {
	  this.graphSectionOffset = value;
   }

   /**
	* Gets the value of the hasBus property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasBus() {
	  return hasBus;
   }

   /**
	* Sets the value of the hasBus property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasBus(JAXBElement<BigInteger> value) {
	  this.hasBus = value;
   }

   /**
	* Gets the value of the hasTrolley property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasTrolley() {
	  return hasTrolley;
   }

   /**
	* Sets the value of the hasTrolley property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasTrolley(JAXBElement<BigInteger> value) {
	  this.hasTrolley = value;
   }

   /**
	* Gets the value of the hasTram property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasTram() {
	  return hasTram;
   }

   /**
	* Sets the value of the hasTram property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasTram(JAXBElement<BigInteger> value) {
	  this.hasTram = value;
   }

   /**
	* Gets the value of the hasSpeedTram property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasSpeedTram() {
	  return hasSpeedTram;
   }

   /**
	* Sets the value of the hasSpeedTram property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasSpeedTram(JAXBElement<BigInteger> value) {
	  this.hasSpeedTram = value;
   }

}
