//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlType;
import java.math.BigInteger;


/**
 * Типы подвижного состава (вместимость)
 * <p>
 * <pre>
 * &lt;?xml version="1.0" encoding="UTF-8"?&gt;&lt;tags xmlns="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:gismgt="http://mappl.ru/2015/XMLSchema/GISMGT" xmlns:p578540_="http://java.sun.com/xml/ns/jaxb/xjc" xmlns:p729618_="http://java.sun.com/xml/ns/jaxb" xmlns:xs="http://www.w3.org/2001/XMLSchema"&gt;&lt;tag&gt;mtrans&lt;/tag&gt;&lt;/tags&gt;
 * </pre>
 * <p>
 * <p>
 * <p>Java class for TVehicleType complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="TVehicleType">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;group ref="{http://mappl.ru/2015/XMLSchema/GISMGT}TDictionaryObject"/>
 *         &lt;element name="name" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TName" minOccurs="0"/>
 *         &lt;element name="shortName" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TName" minOccurs="0"/>
 *         &lt;element name="model" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TModel" minOccurs="0"/>
 *         &lt;element name="routeTransportKind" type="{http://mappl.ru/2015/XMLSchema/GISMGT}RRouteTransportKind" minOccurs="0"/>
 *         &lt;element name="seatingCapacity" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TCapacity" minOccurs="0"/>
 *         &lt;element name="maxCapacity" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TCapacity" minOccurs="0"/>
 *         &lt;element name="effectiveArea" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TArea" minOccurs="0"/>
 *         &lt;element name="fullLoadWeight" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TWeight" minOccurs="0"/>
 *         &lt;element name="dimension" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TDimension" minOccurs="0"/>
 *         &lt;element name="hasFacilitiesForDisabled" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TSign" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "TVehicleType", propOrder = {
	"muid",
	"version",
	"signDeleted",
	"name",
	"shortName",
	"model",
	"routeTransportKind",
	"seatingCapacity",
	"maxCapacity",
	"effectiveArea",
	"fullLoadWeight",
	"dimension",
	"hasFacilitiesForDisabled"
})
public class TVehicleType {

   @XmlElement(required = true)
   protected String muid;
   @XmlElement(defaultValue = "1")
   protected BigInteger version;
   @XmlElementRef(name = "signDeleted", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> signDeleted;
   @XmlElementRef(name = "name", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> name;
   @XmlElementRef(name = "shortName", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> shortName;
   @XmlElementRef(name = "model", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> model;
   @XmlElementRef(name = "routeTransportKind", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<RRouteTransportKind> routeTransportKind;
   @XmlElementRef(name = "seatingCapacity", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Long> seatingCapacity;
   @XmlElementRef(name = "maxCapacity", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Long> maxCapacity;
   @XmlElementRef(name = "effectiveArea", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Float> effectiveArea;
   @XmlElementRef(name = "fullLoadWeight", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<Float> fullLoadWeight;
   @XmlElementRef(name = "dimension", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<String> dimension;
   @XmlElementRef(name = "hasFacilitiesForDisabled", namespace = "http://mappl.ru/2015/XMLSchema/GISMGT", type = JAXBElement.class, required = false)
   protected JAXBElement<BigInteger> hasFacilitiesForDisabled;

   /**
	* Gets the value of the muid property.
	*
	* @return possible object is
	* {@link String }
	*/
   public String getMuid() {
	  return muid;
   }

   /**
	* Sets the value of the muid property.
	*
	* @param value allowed object is
	*              {@link String }
	*/
   public void setMuid(String value) {
	  this.muid = value;
   }

   /**
	* Gets the value of the version property.
	*
	* @return possible object is
	* {@link BigInteger }
	*/
   public BigInteger getVersion() {
	  return version;
   }

   /**
	* Sets the value of the version property.
	*
	* @param value allowed object is
	*              {@link BigInteger }
	*/
   public void setVersion(BigInteger value) {
	  this.version = value;
   }

   /**
	* Gets the value of the signDeleted property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getSignDeleted() {
	  return signDeleted;
   }

   /**
	* Sets the value of the signDeleted property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setSignDeleted(JAXBElement<BigInteger> value) {
	  this.signDeleted = value;
   }

   /**
	* Gets the value of the name property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getName() {
	  return name;
   }

   /**
	* Sets the value of the name property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setName(JAXBElement<String> value) {
	  this.name = value;
   }

   /**
	* Gets the value of the shortName property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getShortName() {
	  return shortName;
   }

   /**
	* Sets the value of the shortName property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setShortName(JAXBElement<String> value) {
	  this.shortName = value;
   }

   /**
	* Gets the value of the model property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getModel() {
	  return model;
   }

   /**
	* Sets the value of the model property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setModel(JAXBElement<String> value) {
	  this.model = value;
   }

   /**
	* Gets the value of the routeTransportKind property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link RRouteTransportKind }{@code >}
	*/
   public JAXBElement<RRouteTransportKind> getRouteTransportKind() {
	  return routeTransportKind;
   }

   /**
	* Sets the value of the routeTransportKind property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link RRouteTransportKind }{@code >}
	*/
   public void setRouteTransportKind(JAXBElement<RRouteTransportKind> value) {
	  this.routeTransportKind = value;
   }

   /**
	* Gets the value of the seatingCapacity property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Long }{@code >}
	*/
   public JAXBElement<Long> getSeatingCapacity() {
	  return seatingCapacity;
   }

   /**
	* Sets the value of the seatingCapacity property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Long }{@code >}
	*/
   public void setSeatingCapacity(JAXBElement<Long> value) {
	  this.seatingCapacity = value;
   }

   /**
	* Gets the value of the maxCapacity property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Long }{@code >}
	*/
   public JAXBElement<Long> getMaxCapacity() {
	  return maxCapacity;
   }

   /**
	* Sets the value of the maxCapacity property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Long }{@code >}
	*/
   public void setMaxCapacity(JAXBElement<Long> value) {
	  this.maxCapacity = value;
   }

   /**
	* Gets the value of the effectiveArea property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public JAXBElement<Float> getEffectiveArea() {
	  return effectiveArea;
   }

   /**
	* Sets the value of the effectiveArea property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public void setEffectiveArea(JAXBElement<Float> value) {
	  this.effectiveArea = value;
   }

   /**
	* Gets the value of the fullLoadWeight property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public JAXBElement<Float> getFullLoadWeight() {
	  return fullLoadWeight;
   }

   /**
	* Sets the value of the fullLoadWeight property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link Float }{@code >}
	*/
   public void setFullLoadWeight(JAXBElement<Float> value) {
	  this.fullLoadWeight = value;
   }

   /**
	* Gets the value of the dimension property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public JAXBElement<String> getDimension() {
	  return dimension;
   }

   /**
	* Sets the value of the dimension property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link String }{@code >}
	*/
   public void setDimension(JAXBElement<String> value) {
	  this.dimension = value;
   }

   /**
	* Gets the value of the hasFacilitiesForDisabled property.
	*
	* @return possible object is
	* {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public JAXBElement<BigInteger> getHasFacilitiesForDisabled() {
	  return hasFacilitiesForDisabled;
   }

   /**
	* Sets the value of the hasFacilitiesForDisabled property.
	*
	* @param value allowed object is
	*              {@link JAXBElement }{@code <}{@link BigInteger }{@code >}
	*/
   public void setHasFacilitiesForDisabled(JAXBElement<BigInteger> value) {
	  this.hasFacilitiesForDisabled = value;
   }

}
