//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2016.06.24 at 01:07:10 PM MSK 
//


package ru.armd.pbk.gismgt.schema;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.datatype.XMLGregorianCalendar;


/**
 * Запрос на изменения по списку типов объектов на определенный период времени
 * <p>
 * <p>Java class for msg_TTypeRequestMessage complex type.
 * <p>
 * <p>The following schema fragment specifies the expected content contained within this class.
 * <p>
 * <pre>
 * &lt;complexType name="msg_TTypeRequestMessage">
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;all>
 *         &lt;element name="header">
 *           &lt;complexType>
 *             &lt;complexContent>
 *               &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *                 &lt;sequence>
 *                   &lt;element name="message-ident" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TMessageIdent" minOccurs="0"/>
 *                   &lt;element name="source" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TMessageSource"/>
 *                   &lt;element name="timestamp" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TMessageTimestamp"/>
 *                   &lt;element name="objectTypes" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TObjectTypes"/>
 *                   &lt;element name="periodStart" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TDateTime"/>
 *                   &lt;element name="periodEnd" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TDateTime"/>
 *                 &lt;/sequence>
 *               &lt;/restriction>
 *             &lt;/complexContent>
 *           &lt;/complexType>
 *         &lt;/element>
 *       &lt;/all>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "msg_TTypeRequestMessage", propOrder = {

})
@XmlRootElement(name = "type-request")
public class TypeRequest {

   @XmlElement(required = true)
   protected TypeRequest.Header header;

   /**
	* Gets the value of the header property.
	*
	* @return possible object is
	* {@link TypeRequest.Header }
	*/
   public TypeRequest.Header getHeader() {
	  return header;
   }

   /**
	* Sets the value of the header property.
	*
	* @param value allowed object is
	*              {@link TypeRequest.Header }
	*/
   public void setHeader(TypeRequest.Header value) {
	  this.header = value;
   }


   /**
	* <p>Java class for anonymous complex type.
	* <p>
	* <p>The following schema fragment specifies the expected content contained within this class.
	* <p>
	* <pre>
	* &lt;complexType>
	*   &lt;complexContent>
	*     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
	*       &lt;sequence>
	*         &lt;element name="message-ident" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TMessageIdent" minOccurs="0"/>
	*         &lt;element name="source" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TMessageSource"/>
	*         &lt;element name="timestamp" type="{http://mappl.ru/2015/XMLSchema/GISMGT}msg_TMessageTimestamp"/>
	*         &lt;element name="objectTypes" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TObjectTypes"/>
	*         &lt;element name="periodStart" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TDateTime"/>
	*         &lt;element name="periodEnd" type="{http://mappl.ru/2015/XMLSchema/GISMGT}TDateTime"/>
	*       &lt;/sequence>
	*     &lt;/restriction>
	*   &lt;/complexContent>
	* &lt;/complexType>
	* </pre>
	*/
   @XmlAccessorType(XmlAccessType.FIELD)
   @XmlType(name = "", propOrder = {
	   "messageIdent",
	   "source",
	   "timestamp",
	   "objectTypes",
	   "periodStart",
	   "periodEnd"
   })
   public static class Header {

	  @XmlElement(name = "message-ident")
	  protected String messageIdent;
	  @XmlElement(required = true)
	  protected String source;
	  @XmlElement(required = true)
	  protected XMLGregorianCalendar timestamp;
	  @XmlElement(required = true)
	  protected TObjectTypes objectTypes;
	  @XmlElement(required = true)
	  protected XMLGregorianCalendar periodStart;
	  @XmlElement(required = true)
	  protected XMLGregorianCalendar periodEnd;

	  /**
	   * Gets the value of the messageIdent property.
	   *
	   * @return possible object is
	   * {@link String }
	   */
	  public String getMessageIdent() {
		 return messageIdent;
	  }

	  /**
	   * Sets the value of the messageIdent property.
	   *
	   * @param value allowed object is
	   *              {@link String }
	   */
	  public void setMessageIdent(String value) {
		 this.messageIdent = value;
	  }

	  /**
	   * Gets the value of the source property.
	   *
	   * @return possible object is
	   * {@link String }
	   */
	  public String getSource() {
		 return source;
	  }

	  /**
	   * Sets the value of the source property.
	   *
	   * @param value allowed object is
	   *              {@link String }
	   */
	  public void setSource(String value) {
		 this.source = value;
	  }

	  /**
	   * Gets the value of the timestamp property.
	   *
	   * @return possible object is
	   * {@link XMLGregorianCalendar }
	   */
	  public XMLGregorianCalendar getTimestamp() {
		 return timestamp;
	  }

	  /**
	   * Sets the value of the timestamp property.
	   *
	   * @param value allowed object is
	   *              {@link XMLGregorianCalendar }
	   */
	  public void setTimestamp(XMLGregorianCalendar value) {
		 this.timestamp = value;
	  }

	  /**
	   * Gets the value of the objectTypes property.
	   *
	   * @return possible object is
	   * {@link TObjectTypes }
	   */
	  public TObjectTypes getObjectTypes() {
		 return objectTypes;
	  }

	  /**
	   * Sets the value of the objectTypes property.
	   *
	   * @param value allowed object is
	   *              {@link TObjectTypes }
	   */
	  public void setObjectTypes(TObjectTypes value) {
		 this.objectTypes = value;
	  }

	  /**
	   * Gets the value of the periodStart property.
	   *
	   * @return possible object is
	   * {@link XMLGregorianCalendar }
	   */
	  public XMLGregorianCalendar getPeriodStart() {
		 return periodStart;
	  }

	  /**
	   * Sets the value of the periodStart property.
	   *
	   * @param value allowed object is
	   *              {@link XMLGregorianCalendar }
	   */
	  public void setPeriodStart(XMLGregorianCalendar value) {
		 this.periodStart = value;
	  }

	  /**
	   * Gets the value of the periodEnd property.
	   *
	   * @return possible object is
	   * {@link XMLGregorianCalendar }
	   */
	  public XMLGregorianCalendar getPeriodEnd() {
		 return periodEnd;
	  }

	  /**
	   * Sets the value of the periodEnd property.
	   *
	   * @param value allowed object is
	   *              {@link XMLGregorianCalendar }
	   */
	  public void setPeriodEnd(XMLGregorianCalendar value) {
		 this.periodEnd = value;
	  }

   }

}
